from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

import numpy as np
import pandas as pd

from config.phase3_2_config import Phase32Config, load_phase3_2_config


# =========================================================
# Phase III.2 — Diagnostics
# Leakage-safe conditional estimator aware version
# Phase III.2D multichannel-aware patch
# =========================================================
#
# Purpose:
#
#   Post-run diagnostic audit for Phase III.2 after the leakage-safe
#   conditional estimator patch and Phase III.2D multichannel activation.
#
# This module does not rerun the experiment.
# It reads outputs generated by:
#
#   python -m src.phase3_2_conditional
#   python -m src.phase3_2_controls
#   python -m src.phase3_2_metrics
#
# It diagnoses:
#
#   - primary vs exploratory results
#   - single-channel III.2C vs multichannel III.2D behavior
#   - conditional lift behavior
#   - ε saturation
#   - BIC / complexity behavior
#   - controls collapse under leakage-safe criteria
#   - multichannel control behavior
#   - failed gates
#   - multiple-comparison guard
#   - final scientific interpretation
#
# Important:
#
#   III.2D is exploratory. It enriches EEG representation using Fpz-Cz + Pz-Oz,
#   but it does not convert exploratory rows into a strong claim unless F7/F8/F12
#   and control criteria are satisfied.
#
#   III.2E remains protocol-only and requires synchronized EEG + QRNG timestamps.


# =========================================================
# Generic helpers
# =========================================================

def _json_default(obj: Any) -> Any:
    if isinstance(obj, Path):
        return str(obj)

    if isinstance(obj, (np.integer,)):
        return int(obj)

    if isinstance(obj, (np.floating,)):
        return float(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    if hasattr(obj, "__dict__"):
        return obj.__dict__

    return str(obj)


def save_json(path: Path, payload: Dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False, default=_json_default)


def load_json(path: Path) -> Dict[str, Any]:
    path = Path(path)

    if not path.exists():
        return {}

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_csv(path: Path) -> pd.DataFrame:
    path = Path(path)

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default

        x = float(value)

        if not np.isfinite(x):
            return default

        return x

    except Exception:
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if pd.isna(value):
            return default

        return int(value)

    except Exception:
        return default


def _as_bool_series(series: pd.Series) -> pd.Series:
    if series.empty:
        return pd.Series([], dtype=bool)

    if series.dtype == bool:
        return series

    return series.astype(str).str.lower().isin(["true", "1", "yes"])


def _safe_records(df: pd.DataFrame) -> List[Dict[str, Any]]:
    if df.empty:
        return []

    return df.replace({np.nan: None}).to_dict(orient="records")


def _select_existing_columns(df: pd.DataFrame, columns: List[str]) -> List[str]:
    return [c for c in columns if c in df.columns]


def _numeric_series(df: pd.DataFrame, col: str, default: float = 0.0) -> pd.Series:
    if df.empty:
        return pd.Series([], dtype=float)

    if col not in df.columns:
        return pd.Series([default] * len(df), index=df.index, dtype=float)

    return pd.to_numeric(df[col], errors="coerce").fillna(default)


def _cfg_float(cfg: Phase32Config, name: str, default: float) -> float:
    return float(getattr(cfg, name, default))


def _cfg_bool(cfg: Phase32Config, name: str, default: bool) -> bool:
    return bool(getattr(cfg, name, default))


# =========================================================
# Paths
# =========================================================

def phase3_2_paths(cfg: Phase32Config) -> Dict[str, Path]:
    results_dir = Path(cfg.results_dir)
    interim_dir = Path(cfg.interim_dir)
    diagnostics_dir = Path(cfg.diagnostics_dir)

    return {
        "runner_report": results_dir / "phase3_2_runner_report.json",
        "runner_summary": results_dir / "phase3_2_runner_summary.txt",
        "gates_json": Path(cfg.gates_json),
        "metrics_table": results_dir / "phase3_2_metrics_table.csv",
        "metrics_summary": results_dir / "phase3_2_metrics_summary.txt",
        "mc_guard": Path(cfg.multiple_comparison_guard_json),

        "conditional_pair_scores": Path(cfg.conditional_results_csv),
        "conditional_model_scores": results_dir / "phase3_2c_conditional_model_scores.csv",
        "conditional_summary": Path(cfg.conditional_summary_json),

        "multichannel_results": Path(cfg.multichannel_results_csv),
        "multichannel_features": Path(cfg.multichannel_features_file),
        "multichannel_inventory": Path(cfg.multichannel_inventory_json),
        "multichannel_summary": Path(cfg.multichannel_summary_json),

        "control_runs": results_dir / "phase3_2_control_runs.csv",
        "control_pair_scores": results_dir / "phase3_2_control_pair_scores.csv",
        "controls_json": Path(cfg.controls_json),

        "regime_inventory": interim_dir / "phase3_2_regime_inventory.csv",
        "lag_inventory": interim_dir / "phase3_2_lag_inventory.csv",
        "feature_specs": interim_dir / "phase3_2_feature_specs.json",
        "loader_metadata": Path(cfg.loader_metadata_file),

        "diagnostics_dir": diagnostics_dir,
    }


# =========================================================
# Conditional row selectors
# =========================================================

def valid_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    if pair_df.empty or "valid" not in pair_df.columns:
        return pd.DataFrame()

    return pair_df[_as_bool_series(pair_df["valid"])].copy()


def primary_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty or "primary" not in valid.columns:
        return pd.DataFrame()

    return valid[_as_bool_series(valid["primary"])].copy()


def is_multichannel_pair_mask(df: pd.DataFrame) -> pd.Series:
    if df.empty:
        return pd.Series([], dtype=bool)

    mask = pd.Series(np.zeros(len(df), dtype=bool), index=df.index)

    for col in ["baseline_model", "augmented_model", "family"]:
        if col not in df.columns:
            continue

        text = df[col].astype(str)

        mask |= text.str.startswith("D")
        mask |= text.str.contains("MCEEG", case=False, na=False)
        mask |= text.str.contains("multichannel", case=False, na=False)

    return mask


def multichannel_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    return valid[is_multichannel_pair_mask(valid)].copy()


def single_channel_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    return valid[~is_multichannel_pair_mask(valid)].copy()


def positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    lift = _numeric_series(valid, "conditional_lift")
    return valid[lift > 0.0].copy()


def primary_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    primary = primary_pair_rows(pair_df)

    if primary.empty:
        return pd.DataFrame()

    lift = _numeric_series(primary, "conditional_lift")
    return primary[lift > 0.0].copy()


def multichannel_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    mc = multichannel_pair_rows(pair_df)

    if mc.empty:
        return pd.DataFrame()

    lift = _numeric_series(mc, "conditional_lift")
    return mc[lift > 0.0].copy()


def single_channel_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    sc = single_channel_pair_rows(pair_df)

    if sc.empty:
        return pd.DataFrame()

    lift = _numeric_series(sc, "conditional_lift")
    return sc[lift > 0.0].copy()


def strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    lift = _numeric_series(valid, "conditional_lift")
    eps = _numeric_series(valid, "augmented_eps_test")
    frac = _numeric_series(valid, "fraction_positive_lift")
    bic = _numeric_series(valid, "bic_improvement")

    strong = valid[
        (lift >= float(cfg.conditional_lift_min))
        & (eps >= float(cfg.strong_eps_min))
        & (frac >= float(cfg.subject_effect_fraction))
        & (bic >= 0.0)
    ].copy()

    return strong


def primary_strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty or "primary" not in strong.columns:
        return pd.DataFrame()

    return strong[_as_bool_series(strong["primary"])].copy()


def multichannel_strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty:
        return pd.DataFrame()

    return strong[is_multichannel_pair_mask(strong)].copy()


def exploratory_lift_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    positive = positive_lift_rows(pair_df)

    if positive.empty:
        return pd.DataFrame()

    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty:
        return positive.copy()

    return positive[~positive.index.isin(set(strong.index.tolist()))].copy()


def high_epsilon_zero_lift_rows(
    pair_df: pd.DataFrame,
    cfg: Phase32Config,
) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    eps_threshold = _cfg_float(cfg, "eps_saturation_value", 0.80)

    eps = _numeric_series(valid, "augmented_eps_test")
    lift = _numeric_series(valid, "conditional_lift")

    return valid[(eps >= eps_threshold) & (lift <= 0.0)].copy()


def best_rows_by_metric(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    metrics = [
        ("conditional_lift", True),
        ("augmented_eps_test", True),
        ("baseline_eps_test", True),
        ("ll_improvement", True),
        ("bic_improvement", True),
        ("aic_improvement", True),
        ("fraction_positive_lift", True),
    ]

    rows: List[Dict[str, Any]] = []

    for metric, descending in metrics:
        if metric not in valid.columns:
            continue

        sorted_df = valid.sort_values(metric, ascending=not descending).reset_index(drop=True)

        if sorted_df.empty:
            continue

        row = sorted_df.iloc[0].to_dict()
        row["selected_by"] = metric
        rows.append(row)

    if not rows:
        return pd.DataFrame()

    best_df = pd.DataFrame(rows)

    preferred_columns = [
        "selected_by",
        "regime",
        "lag_epochs",
        "lag_label",
        "family",
        "baseline_model",
        "augmented_model",
        "primary",
        "valid",
        "baseline_eps_test",
        "augmented_eps_test",
        "conditional_lift",
        "fraction_positive_lift",
        "ll_improvement",
        "bic_improvement",
        "aic_improvement",
        "n_subjects_evaluated",
        "n_subjects_positive_lift",
        "reason",
    ]

    cols = _select_existing_columns(best_df, preferred_columns)
    return best_df[cols].copy()


def best_multichannel_rows_by_metric(pair_df: pd.DataFrame) -> pd.DataFrame:
    mc = multichannel_pair_rows(pair_df)

    if mc.empty:
        return pd.DataFrame()

    return best_rows_by_metric(mc)


# =========================================================
# Saturation diagnostics
# =========================================================

def summarize_model_saturation(
    model_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    if model_df.empty:
        return {
            "available": False,
            "reason": "model_scores_missing",
        }

    eps_saturation_value = _cfg_float(cfg, "eps_saturation_value", 0.80)

    eps_cols = [
        col for col in ["eps_candidate", "eps_calib", "eps_test"]
        if col in model_df.columns
    ]

    if not eps_cols:
        return {
            "available": False,
            "reason": "no_epsilon_columns_available",
        }

    summary: Dict[str, Any] = {
        "available": True,
        "eps_saturation_value": eps_saturation_value,
        "n_model_rows": int(len(model_df)),
        "columns": {},
    }

    for col in eps_cols:
        values = _numeric_series(model_df, col)
        saturated = values >= eps_saturation_value

        summary["columns"][col] = {
            "max": float(values.max()) if len(values) else 0.0,
            "mean": float(values.mean()) if len(values) else 0.0,
            "n_saturated": int(saturated.sum()),
            "saturation_fraction": float(np.mean(saturated.to_numpy(dtype=bool))) if len(saturated) else 0.0,
        }

    if "eps_saturated" in model_df.columns:
        explicit = _as_bool_series(model_df["eps_saturated"])
        summary["explicit_eps_saturated"] = {
            "n_saturated": int(explicit.sum()),
            "saturation_fraction": float(np.mean(explicit.to_numpy(dtype=bool))) if len(explicit) else 0.0,
        }

    max_fraction = max(
        item.get("saturation_fraction", 0.0)
        for item in summary["columns"].values()
    )

    warning_fraction = _cfg_float(cfg, "eps_saturation_warning_fraction", 0.50)

    summary["max_saturation_fraction"] = float(max_fraction)
    summary["warning_fraction"] = float(warning_fraction)
    summary["warning"] = bool(max_fraction >= warning_fraction)
    summary["reason"] = "epsilon_saturation_warning" if summary["warning"] else "ok"

    return summary


def summarize_pair_saturation(
    pair_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return {
            "available": False,
            "reason": "no_valid_pair_rows",
        }

    eps_saturation_value = _cfg_float(cfg, "eps_saturation_value", 0.80)
    warning_fraction = _cfg_float(cfg, "eps_saturation_warning_fraction", 0.50)

    baseline_eps = _numeric_series(valid, "baseline_eps_test")
    augmented_eps = _numeric_series(valid, "augmented_eps_test")

    baseline_sat = baseline_eps >= eps_saturation_value
    augmented_sat = augmented_eps >= eps_saturation_value
    either_sat = baseline_sat | augmented_sat
    both_sat = baseline_sat & augmented_sat

    either_fraction = float(np.mean(either_sat.to_numpy(dtype=bool))) if len(either_sat) else 0.0
    both_fraction = float(np.mean(both_sat.to_numpy(dtype=bool))) if len(both_sat) else 0.0

    return {
        "available": True,
        "eps_saturation_value": float(eps_saturation_value),
        "warning_fraction": float(warning_fraction),
        "n_valid_pair_rows": int(len(valid)),
        "max_baseline_eps_test": float(baseline_eps.max()) if len(baseline_eps) else 0.0,
        "max_augmented_eps_test": float(augmented_eps.max()) if len(augmented_eps) else 0.0,
        "n_either_saturated": int(either_sat.sum()),
        "n_both_saturated": int(both_sat.sum()),
        "either_saturation_fraction": either_fraction,
        "both_saturation_fraction": both_fraction,
        "warning": bool(either_fraction >= warning_fraction),
        "reason": "pair_level_epsilon_saturation_warning" if either_fraction >= warning_fraction else "ok",
    }


# =========================================================
# Conditional diagnostics
# =========================================================

def summarize_conditional(
    pair_df: pd.DataFrame,
    model_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)
    primary = primary_pair_rows(pair_df)
    positive = positive_lift_rows(pair_df)
    primary_positive = primary_positive_lift_rows(pair_df)
    strong = strong_candidate_rows(pair_df, cfg)
    primary_strong = primary_strong_candidate_rows(pair_df, cfg)
    exploratory = exploratory_lift_rows(pair_df, cfg)
    high_eps_zero_lift = high_epsilon_zero_lift_rows(pair_df, cfg)

    single_channel = single_channel_pair_rows(pair_df)
    single_channel_positive = single_channel_positive_lift_rows(pair_df)

    multichannel = multichannel_pair_rows(pair_df)
    multichannel_positive = multichannel_positive_lift_rows(pair_df)
    multichannel_strong = multichannel_strong_candidate_rows(pair_df, cfg)

    summary: Dict[str, Any] = {
        "available": not pair_df.empty,
        "n_rows": int(len(pair_df)),
        "n_valid_rows": int(len(valid)),
        "n_primary_rows": int(len(primary)),
        "n_positive_lift_rows": int(len(positive)),
        "n_primary_positive_lift_rows": int(len(primary_positive)),
        "n_exploratory_lift_rows": int(len(exploratory)),
        "n_strong_candidate_rows": int(len(strong)),
        "n_primary_strong_candidate_rows": int(len(primary_strong)),
        "n_high_epsilon_zero_lift_rows": int(len(high_eps_zero_lift)),

        "n_single_channel_rows": int(len(single_channel)),
        "n_single_channel_positive_lift_rows": int(len(single_channel_positive)),

        "n_multichannel_rows": int(len(multichannel)),
        "n_multichannel_positive_lift_rows": int(len(multichannel_positive)),
        "n_multichannel_strong_candidate_rows": int(len(multichannel_strong)),

        "thresholds": {
            "conditional_lift_min": float(cfg.conditional_lift_min),
            "strong_eps_min": float(cfg.strong_eps_min),
            "subject_effect_fraction": float(cfg.subject_effect_fraction),
            "eps_saturation_value": _cfg_float(cfg, "eps_saturation_value", 0.80),
        },
        "model_saturation": summarize_model_saturation(model_df, cfg),
        "pair_saturation": summarize_pair_saturation(pair_df, cfg),
        "single_channel_pair_saturation": summarize_pair_saturation(single_channel, cfg),
        "multichannel_pair_saturation": summarize_pair_saturation(multichannel, cfg),
        "interpretation": "",
    }

    if valid.empty:
        summary["interpretation"] = "No valid conditional rows were available."
        return summary

    lift = _numeric_series(valid, "conditional_lift")
    eps = _numeric_series(valid, "augmented_eps_test")
    frac = _numeric_series(valid, "fraction_positive_lift")
    bic = _numeric_series(valid, "bic_improvement")
    ll = _numeric_series(valid, "ll_improvement")

    mc_lift = _numeric_series(multichannel, "conditional_lift") if not multichannel.empty else pd.Series([], dtype=float)
    mc_eps = _numeric_series(multichannel, "augmented_eps_test") if not multichannel.empty else pd.Series([], dtype=float)
    mc_frac = _numeric_series(multichannel, "fraction_positive_lift") if not multichannel.empty else pd.Series([], dtype=float)
    mc_bic = _numeric_series(multichannel, "bic_improvement") if not multichannel.empty else pd.Series([], dtype=float)
    mc_ll = _numeric_series(multichannel, "ll_improvement") if not multichannel.empty else pd.Series([], dtype=float)

    summary.update(
        {
            "max_conditional_lift": float(lift.max()) if len(lift) else 0.0,
            "max_augmented_eps_test": float(eps.max()) if len(eps) else 0.0,
            "max_fraction_positive_lift": float(frac.max()) if len(frac) else 0.0,
            "best_bic_improvement": float(bic.max()) if len(bic) else 0.0,
            "best_ll_improvement": float(ll.max()) if len(ll) else 0.0,

            "max_multichannel_conditional_lift": float(mc_lift.max()) if len(mc_lift) else 0.0,
            "max_multichannel_augmented_eps_test": float(mc_eps.max()) if len(mc_eps) else 0.0,
            "max_multichannel_fraction_positive_lift": float(mc_frac.max()) if len(mc_frac) else 0.0,
            "best_multichannel_bic_improvement": float(mc_bic.max()) if len(mc_bic) else 0.0,
            "best_multichannel_ll_improvement": float(mc_ll.max()) if len(mc_ll) else 0.0,

            "primary_rows": _safe_records(primary),
            "positive_lift_rows": _safe_records(positive),
            "primary_positive_lift_rows": _safe_records(primary_positive),
            "exploratory_lift_rows": _safe_records(exploratory),
            "strong_candidate_rows": _safe_records(strong),
            "primary_strong_candidate_rows": _safe_records(primary_strong),
            "high_epsilon_zero_lift_rows": _safe_records(high_eps_zero_lift),

            "single_channel_rows": _safe_records(single_channel),
            "single_channel_positive_lift_rows": _safe_records(single_channel_positive),
            "multichannel_rows": _safe_records(multichannel),
            "multichannel_positive_lift_rows": _safe_records(multichannel_positive),
            "multichannel_strong_candidate_rows": _safe_records(multichannel_strong),
        }
    )

    if len(primary_strong) > 0:
        summary["interpretation"] = (
            "At least one primary strong candidate row exists before final replication review."
        )
    elif len(strong) > 0:
        summary["interpretation"] = (
            "Strong candidate rows exist only outside the primary registered structure."
        )
    elif len(multichannel_positive) > 0:
        summary["interpretation"] = (
            "Positive conditional lift rows exist, including Phase III.2D multichannel rows. "
            "They remain exploratory because they do not satisfy all registered criteria "
            "simultaneously."
        )
    elif len(positive) > 0:
        summary["interpretation"] = (
            "Positive conditional lift rows exist, but they remain exploratory because they "
            "do not satisfy all registered criteria simultaneously."
        )
    else:
        summary["interpretation"] = (
            "No positive conditional lift rows were detected."
        )

    return summary


# =========================================================
# Phase III.2D multichannel diagnostics
# =========================================================

def summarize_multichannel_artifacts(
    multichannel_summary_json: Mapping[str, Any],
    multichannel_inventory_json: Mapping[str, Any],
    multichannel_features_df: pd.DataFrame,
) -> Dict[str, Any]:
    summary_payload = multichannel_summary_json.get("summary", {}) if multichannel_summary_json else {}
    inventory_payload = multichannel_inventory_json if multichannel_inventory_json else {}

    source_columns = inventory_payload.get("source_columns", {}) if inventory_payload else {}

    return {
        "summary_available": bool(multichannel_summary_json),
        "inventory_available": bool(multichannel_inventory_json),
        "features_available": not multichannel_features_df.empty,

        "multichannel_available": bool(source_columns.get("multichannel_available", False)),
        "delta_secondary_source_column": source_columns.get("delta_secondary_source_column"),
        "alpha_secondary_source_column": source_columns.get("alpha_secondary_source_column"),
        "true_delta_secondary_available": source_columns.get("true_delta_secondary_available"),
        "true_alpha_secondary_available": source_columns.get("true_alpha_secondary_available"),

        "n_rows_features": int(len(multichannel_features_df)) if not multichannel_features_df.empty else summary_payload.get("n_rows"),
        "n_subjects_features": (
            int(multichannel_features_df["subject_id"].nunique())
            if not multichannel_features_df.empty and "subject_id" in multichannel_features_df.columns
            else summary_payload.get("n_subjects")
        ),

        "state_n_unique": inventory_payload.get("state_n_unique"),
        "next_state_n_unique": inventory_payload.get("next_state_n_unique"),
        "info_bin_n_unique": inventory_payload.get("info_bin_n_unique"),

        "valid_multichannel_next_state_rows": inventory_payload.get("valid_multichannel_next_state_rows"),
        "valid_multichannel_conditional_rows": inventory_payload.get("valid_multichannel_conditional_rows"),

        "density": inventory_payload.get("density", {}),
        "warnings": inventory_payload.get("warnings", []),
    }


def summarize_phase3_2d_multichannel(
    pair_df: pd.DataFrame,
    model_df: pd.DataFrame,
    control_pair_df: pd.DataFrame,
    control_runs_df: pd.DataFrame,
    multichannel_results_df: pd.DataFrame,
    multichannel_summary_json: Mapping[str, Any],
    multichannel_inventory_json: Mapping[str, Any],
    multichannel_features_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    mc_rows = multichannel_pair_rows(pair_df)
    mc_positive = multichannel_positive_lift_rows(pair_df)
    mc_strong = multichannel_strong_candidate_rows(pair_df, cfg)
    mc_best = best_multichannel_rows_by_metric(pair_df)

    if not multichannel_results_df.empty:
        mc_results_valid = valid_pair_rows(multichannel_results_df)
    else:
        mc_results_valid = mc_rows.copy()

    mc_control_pairs = (
        control_pair_df[is_multichannel_pair_mask(control_pair_df)].copy()
        if not control_pair_df.empty
        else pd.DataFrame()
    )

    mc_control_positive = pd.DataFrame()
    mc_control_strong = pd.DataFrame()

    if not mc_control_pairs.empty:
        valid_control_pairs = valid_pair_rows(mc_control_pairs)

        if not valid_control_pairs.empty:
            lift = _numeric_series(valid_control_pairs, "conditional_lift")
            mc_control_positive = valid_control_pairs[lift > 0.0].copy()
            mc_control_strong = strong_candidate_rows(valid_control_pairs, cfg)

    control_summary: Dict[str, Any] = {
        "available": not control_runs_df.empty,
        "n_control_run_rows": int(len(control_runs_df)),
        "n_control_pair_rows": int(len(control_pair_df)) if not control_pair_df.empty else 0,
        "n_multichannel_control_pair_rows": int(len(mc_control_pairs)),
        "n_multichannel_control_positive_lift_rows": int(len(mc_control_positive)),
        "n_multichannel_control_strong_candidate_rows": int(len(mc_control_strong)),
    }

    if not control_runs_df.empty:
        for col in [
            "n_multichannel_pair_rows",
            "n_multichannel_positive_lift_rows",
            "n_multichannel_strong_candidate_rows",
        ]:
            if col in control_runs_df.columns:
                control_summary[f"total_{col}"] = int(
                    pd.to_numeric(control_runs_df[col], errors="coerce").fillna(0).sum()
                )

        if "collapsed_overall" in control_runs_df.columns:
            collapsed = _as_bool_series(control_runs_df["collapsed_overall"])
            control_summary["fraction_controls_collapsed_overall"] = float(
                np.mean(collapsed.to_numpy(dtype=bool))
            ) if len(collapsed) else 0.0

    mc_lift = _numeric_series(mc_rows, "conditional_lift") if not mc_rows.empty else pd.Series([], dtype=float)
    mc_eps = _numeric_series(mc_rows, "augmented_eps_test") if not mc_rows.empty else pd.Series([], dtype=float)
    mc_frac = _numeric_series(mc_rows, "fraction_positive_lift") if not mc_rows.empty else pd.Series([], dtype=float)
    mc_bic = _numeric_series(mc_rows, "bic_improvement") if not mc_rows.empty else pd.Series([], dtype=float)
    mc_ll = _numeric_series(mc_rows, "ll_improvement") if not mc_rows.empty else pd.Series([], dtype=float)

    artifact_summary = summarize_multichannel_artifacts(
        multichannel_summary_json=multichannel_summary_json,
        multichannel_inventory_json=multichannel_inventory_json,
        multichannel_features_df=multichannel_features_df,
    )

    interpretation = ""

    if mc_rows.empty:
        interpretation = "Phase III.2D multichannel rows were not found in conditional outputs."
    elif len(mc_positive) == 0:
        interpretation = (
            "Phase III.2D produced no positive conditional lift rows under the current estimator."
        )
    elif len(mc_strong) == 0:
        interpretation = (
            "Phase III.2D produced exploratory positive lift rows, but no multichannel row "
            "satisfied lift, epsilon, subject-consistency and BIC criteria simultaneously."
        )
    else:
        interpretation = (
            "Phase III.2D produced multichannel strong-candidate rows before independent replication review."
        )

    return {
        "enabled_in_config": bool(cfg.run_multichannel_analysis and cfg.use_multichannel_eeg),
        "protocol_relation": {
            "phase3_2d_status": "active_exploratory",
            "phase3_2e_status": "protocol_only",
            "phase3_2e_requires_synchronized_eeg_qrng": bool(cfg.phase3_2e_requires_real_time_sync),
        },
        "artifact_summary": artifact_summary,

        "n_multichannel_rows": int(len(mc_rows)),
        "n_multichannel_results_rows": int(len(mc_results_valid)),
        "n_multichannel_positive_lift_rows": int(len(mc_positive)),
        "n_multichannel_strong_candidate_rows": int(len(mc_strong)),

        "max_multichannel_conditional_lift": float(mc_lift.max()) if len(mc_lift) else 0.0,
        "max_multichannel_augmented_eps_test": float(mc_eps.max()) if len(mc_eps) else 0.0,
        "max_multichannel_fraction_positive_lift": float(mc_frac.max()) if len(mc_frac) else 0.0,
        "best_multichannel_bic_improvement": float(mc_bic.max()) if len(mc_bic) else 0.0,
        "best_multichannel_ll_improvement": float(mc_ll.max()) if len(mc_ll) else 0.0,

        "multichannel_pair_saturation": summarize_pair_saturation(mc_rows, cfg),
        "best_multichannel_rows_by_metric": _safe_records(mc_best),
        "multichannel_positive_lift_rows": _safe_records(mc_positive),
        "multichannel_strong_candidate_rows": _safe_records(mc_strong),

        "control_summary": control_summary,
        "interpretation": interpretation,
    }


# =========================================================
# Control diagnostics
# =========================================================

def summarize_control_runs(
    control_runs_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    if control_runs_df.empty:
        return {
            "available": False,
            "reason": "control_runs_missing",
            "interpretation": "No control run CSV was found.",
        }

    rows: List[Dict[str, Any]] = []

    for control_type, group in control_runs_df.groupby("control_type", sort=True):
        valid = group[_as_bool_series(group["valid"])] if "valid" in group.columns else group.copy()

        if valid.empty:
            rows.append(
                {
                    "control_type": str(control_type),
                    "n_runs": int(len(group)),
                    "n_valid_runs": 0,
                    "median_max_baseline_eps_test": 0.0,
                    "median_max_augmented_eps_test": 0.0,
                    "max_augmented_eps_test": 0.0,
                    "median_max_lift": 0.0,
                    "max_lift": 0.0,
                    "median_max_bic_improvement": 0.0,
                    "max_bic_improvement": 0.0,
                    "median_eps_saturation_fraction": 0.0,
                    "max_eps_saturation_fraction": 0.0,
                    "total_multichannel_pair_rows": 0,
                    "total_multichannel_positive_lift_rows": 0,
                    "total_multichannel_strong_candidate_rows": 0,
                    "fraction_collapsed_overall": 0.0,
                    "passed_estimate": False,
                    "reason": "no_valid_runs",
                }
            )
            continue

        baseline_eps = _numeric_series(valid, "max_baseline_eps_test")
        augmented_eps = _numeric_series(valid, "max_augmented_eps_test")
        max_lift = _numeric_series(valid, "max_conditional_lift")
        max_bic = _numeric_series(valid, "max_bic_improvement")
        sat_frac = _numeric_series(valid, "eps_saturation_fraction")

        if "collapsed_overall" in valid.columns:
            collapsed = _as_bool_series(valid["collapsed_overall"])
        else:
            frac = _numeric_series(valid, "max_fraction_positive_lift")
            n_strong = _numeric_series(valid, "n_strong_candidate_rows")
            collapsed = (
                (max_lift <= float(cfg.control_tol))
                & (max_bic <= 0.0)
                & (frac < float(cfg.subject_effect_fraction))
                & (n_strong.astype(int) == 0)
            )

        fraction_collapsed = float(np.mean(collapsed.to_numpy(dtype=bool))) if len(collapsed) else 0.0
        passed_estimate = fraction_collapsed >= float(cfg.required_control_fraction)

        total_mc_pair = 0
        total_mc_positive = 0
        total_mc_strong = 0

        for col, target in [
            ("n_multichannel_pair_rows", "pair"),
            ("n_multichannel_positive_lift_rows", "positive"),
            ("n_multichannel_strong_candidate_rows", "strong"),
        ]:
            if col not in valid.columns:
                continue

            value = int(pd.to_numeric(valid[col], errors="coerce").fillna(0).sum())

            if target == "pair":
                total_mc_pair = value
            elif target == "positive":
                total_mc_positive = value
            elif target == "strong":
                total_mc_strong = value

        rows.append(
            {
                "control_type": str(control_type),
                "n_runs": int(len(group)),
                "n_valid_runs": int(len(valid)),
                "median_max_baseline_eps_test": float(baseline_eps.median()) if len(baseline_eps) else 0.0,
                "median_max_augmented_eps_test": float(augmented_eps.median()) if len(augmented_eps) else 0.0,
                "mean_max_augmented_eps_test": float(augmented_eps.mean()) if len(augmented_eps) else 0.0,
                "max_augmented_eps_test": float(augmented_eps.max()) if len(augmented_eps) else 0.0,
                "median_max_lift": float(max_lift.median()) if len(max_lift) else 0.0,
                "mean_max_lift": float(max_lift.mean()) if len(max_lift) else 0.0,
                "max_lift": float(max_lift.max()) if len(max_lift) else 0.0,
                "median_max_bic_improvement": float(max_bic.median()) if len(max_bic) else 0.0,
                "max_bic_improvement": float(max_bic.max()) if len(max_bic) else 0.0,
                "median_eps_saturation_fraction": float(sat_frac.median()) if len(sat_frac) else 0.0,
                "max_eps_saturation_fraction": float(sat_frac.max()) if len(sat_frac) else 0.0,
                "total_multichannel_pair_rows": total_mc_pair,
                "total_multichannel_positive_lift_rows": total_mc_positive,
                "total_multichannel_strong_candidate_rows": total_mc_strong,
                "fraction_collapsed_overall": fraction_collapsed,
                "required_control_fraction": float(cfg.required_control_fraction),
                "control_tol": float(cfg.control_tol),
                "passed_estimate": bool(passed_estimate),
                "reason": "ok" if passed_estimate else "control_effect_survived",
            }
        )

    breakdown = pd.DataFrame(rows)
    failed = breakdown[breakdown["passed_estimate"] == False].copy()

    return {
        "available": True,
        "n_control_types": int(len(breakdown)),
        "n_failed_control_types": int(len(failed)),
        "failed_control_types": failed["control_type"].tolist() if not failed.empty else [],
        "control_breakdown": breakdown.to_dict(orient="records"),
        "total_multichannel_pair_rows": int(breakdown["total_multichannel_pair_rows"].sum()) if "total_multichannel_pair_rows" in breakdown.columns else 0,
        "total_multichannel_positive_lift_rows": int(breakdown["total_multichannel_positive_lift_rows"].sum()) if "total_multichannel_positive_lift_rows" in breakdown.columns else 0,
        "total_multichannel_strong_candidate_rows": int(breakdown["total_multichannel_strong_candidate_rows"].sum()) if "total_multichannel_strong_candidate_rows" in breakdown.columns else 0,
        "interpretation": (
            "All control types collapsed under the leakage-safe control criteria, including Phase III.2D multichannel-aware controls."
            if failed.empty
            else "At least one negative control did not collapse under the leakage-safe control criteria."
        ),
    }


def summarize_controls_json(controls_json: Mapping[str, Any]) -> Dict[str, Any]:
    if not controls_json:
        return {
            "available": False,
            "reason": "controls_json_missing",
        }

    summary = controls_json.get("summary", controls_json)

    return {
        "available": True,
        "module": controls_json.get("module"),
        "module_detail": controls_json.get("module_detail"),
        "passed": bool(summary.get("passed", False)),
        "failed_control_types": summary.get("failed_control_types", []),
        "n_control_types": summary.get("n_control_types"),
        "raw_summary": summary,
    }


# =========================================================
# Gates diagnostics
# =========================================================

def summarize_gates(
    gates_json: Mapping[str, Any],
    metrics_table_df: pd.DataFrame,
) -> Dict[str, Any]:
    if gates_json:
        final_status = gates_json.get("final_status", {})
        gates = gates_json.get("gates", [])
        epsilon_saturation = gates_json.get("epsilon_saturation", {})
    else:
        final_status = {}
        gates = metrics_table_df.to_dict(orient="records") if not metrics_table_df.empty else []
        epsilon_saturation = {}

    passed: List[str] = []
    failed: List[str] = []
    not_evaluated: List[str] = []
    warnings: List[str] = []

    for gate in gates:
        status = str(gate.get("status", "")).upper()
        name = str(gate.get("gate", ""))

        if status == "PASS":
            passed.append(name)
        elif status == "FAIL":
            failed.append(name)
        elif status == "NOT_EVALUATED":
            not_evaluated.append(name)
        elif status == "WARN":
            warnings.append(name)

    return {
        "available": bool(gates),
        "final_status": final_status,
        "passed_gates": passed,
        "failed_gates": failed,
        "not_evaluated_gates": not_evaluated,
        "warning_gates": warnings,
        "gates": gates,
        "epsilon_saturation": epsilon_saturation,
    }


# =========================================================
# Regime / lag diagnostics
# =========================================================

def summarize_regime_and_lag_inventory(
    regime_df: pd.DataFrame,
    lag_df: pd.DataFrame,
) -> Dict[str, Any]:
    summary: Dict[str, Any] = {
        "regime_inventory_available": not regime_df.empty,
        "lag_inventory_available": not lag_df.empty,
    }

    if not regime_df.empty:
        valid_col = _as_bool_series(regime_df["valid"]) if "valid" in regime_df.columns else pd.Series([], dtype=bool)

        summary["regimes"] = {
            "n_regimes": int(len(regime_df)),
            "n_valid_regimes": int(valid_col.sum()) if not valid_col.empty else 0,
            "valid_regimes": regime_df.loc[valid_col, "regime"].astype(str).tolist() if "regime" in regime_df.columns and not valid_col.empty else [],
            "rows": _safe_records(regime_df),
        }

    if not lag_df.empty:
        valid_col = _as_bool_series(lag_df["valid"]) if "valid" in lag_df.columns else pd.Series([], dtype=bool)

        summary["lags"] = {
            "n_lagged_frames": int(len(lag_df)),
            "n_valid_lagged_frames": int(valid_col.sum()) if not valid_col.empty else 0,
            "rows": _safe_records(lag_df),
        }

    return summary


# =========================================================
# Final interpretation
# =========================================================

def build_final_diagnostic_interpretation(
    conditional_summary: Mapping[str, Any],
    controls_summary: Mapping[str, Any],
    gates_summary: Mapping[str, Any],
    multichannel_summary: Mapping[str, Any],
    cfg: Phase32Config,
) -> Dict[str, Any]:
    final_status = gates_summary.get("final_status", {})
    status = final_status.get("status", "unknown")

    n_positive = _safe_int(conditional_summary.get("n_positive_lift_rows"))
    n_primary_positive = _safe_int(conditional_summary.get("n_primary_positive_lift_rows"))
    n_strong = _safe_int(conditional_summary.get("n_strong_candidate_rows"))
    n_primary_strong = _safe_int(conditional_summary.get("n_primary_strong_candidate_rows"))

    n_mc_positive = _safe_int(multichannel_summary.get("n_multichannel_positive_lift_rows"))
    n_mc_strong = _safe_int(multichannel_summary.get("n_multichannel_strong_candidate_rows"))

    controls_failed = _safe_int(controls_summary.get("n_failed_control_types")) > 0

    failed_gates = gates_summary.get("failed_gates", [])
    warning_gates = gates_summary.get("warning_gates", [])
    not_eval = gates_summary.get("not_evaluated_gates", [])

    if status == "candidate_signal":
        headline = "Phase III.2 produced a primary candidate signal."
    elif status == "blocked_by_controls":
        headline = "Phase III.2 is blocked by controls."
    elif status == "exploratory_lead_with_saturation_warning":
        headline = "Phase III.2 produced exploratory leads with ε saturation warning."
    elif status == "exploratory_lead_only":
        headline = "Phase III.2 produced exploratory leads only."
    elif status == "conditional_null_result":
        headline = "Phase III.2 produced a clean conditional null result."
    elif status == "pending_controls_exploratory_lead":
        headline = "Phase III.2 has exploratory leads but controls are pending."
    else:
        headline = "Phase III.2 produced a non-confirmatory result."

    scientific_read: List[str] = []

    if n_positive > 0:
        scientific_read.append(
            f"Positive conditional lift rows were detected: {n_positive}. "
            f"Primary positive rows: {n_primary_positive}."
        )
    else:
        scientific_read.append(
            "No positive conditional lift rows were detected."
        )

    if n_mc_positive > 0:
        scientific_read.append(
            f"Phase III.2D multichannel EEG produced exploratory positive lift rows: {n_mc_positive}."
        )
    else:
        scientific_read.append(
            "Phase III.2D multichannel EEG did not produce positive lift rows."
        )

    if n_strong == 0:
        scientific_read.append(
            "No strong candidate rows satisfied lift, epsilon, subject-consistency and BIC criteria simultaneously."
        )
    else:
        scientific_read.append(
            f"Strong candidate rows detected: {n_strong}. Primary strong candidates: {n_primary_strong}."
        )

    if n_mc_strong == 0:
        scientific_read.append(
            "No Phase III.2D multichannel row satisfied all strong-candidate criteria."
        )
    else:
        scientific_read.append(
            f"Phase III.2D multichannel strong candidates detected: {n_mc_strong}."
        )

    if controls_failed:
        scientific_read.append(
            "At least one negative control did not collapse; strong interpretation is blocked."
        )
    else:
        scientific_read.append(
            "Negative controls collapsed under the leakage-safe criteria, including multichannel-aware controls."
        )

    if "F7" in failed_gates:
        scientific_read.append(
            "F7 failed: subject-level consistency was insufficient for a strong claim."
        )

    if "F8" in failed_gates:
        scientific_read.append(
            "F8 failed: the augmented conditional model was not favored by BIC."
        )

    if "F12" in warning_gates:
        scientific_read.append(
            "F12 warning: ε saturation remains present and must be treated as a diagnostic limitation."
        )

    if not_eval:
        scientific_read.append(
            f"Not evaluated in this standalone diagnostic run: {not_eval}."
        )

    scientific_read.append(
        "Phase III.2E remains protocol-only because Sleep-EDF and ANU QRNG were not synchronously co-acquired."
    )

    if status == "exploratory_lead_with_saturation_warning":
        recommendation = (
            "Treat Phase III.2A/B/C/D as an exploratory lead only. Controls passed, including "
            "multichannel-aware controls, but F7/F8 failed and F12 raised an ε saturation warning. "
            "Do not claim EEG-RNG coupling. Document III.2D as an exploratory multichannel enrichment "
            "that increased positive-lift rows but did not satisfy subject-consistency, BIC and saturation "
            "requirements. Keep III.2E as a future synchronized EEG + QRNG protocol."
        )
    elif status == "conditional_null_result":
        recommendation = (
            "Treat Phase III.2 as a clean conditional null result under the current public-data design."
        )
    elif status == "blocked_by_controls":
        recommendation = (
            "Do not proceed to a positive interpretation. Inspect control-level outputs before extending the phase."
        )
    else:
        recommendation = (
            "Treat Phase III.2 as non-confirmatory unless future diagnostics satisfy controls, subject consistency, BIC and saturation criteria."
        )

    return {
        "headline": headline,
        "status": status,
        "scientific_read": scientific_read,
        "recommendation": recommendation,
    }


# =========================================================
# Text report
# =========================================================

def build_diagnostics_summary_text(report: Mapping[str, Any]) -> str:
    lines: List[str] = []

    lines.append("=" * 78)
    lines.append("CDR Phase III.2 — Diagnostics Summary")
    lines.append("Leakage-safe conditional estimator aware version")
    lines.append("Phase III.2D multichannel-aware")
    lines.append("=" * 78)
    lines.append("")

    final = report.get("final_interpretation", {})
    lines.append("Final interpretation")
    lines.append("-" * 78)
    lines.append(f"headline: {final.get('headline')}")
    lines.append(f"status: {final.get('status')}")
    lines.append("")

    for item in final.get("scientific_read", []):
        lines.append(f"- {item}")

    lines.append("")
    lines.append(f"recommendation: {final.get('recommendation')}")
    lines.append("")

    conditional = report.get("conditional_diagnostics", {})
    lines.append("Conditional diagnostics")
    lines.append("-" * 78)
    lines.append(f"n_rows: {conditional.get('n_rows')}")
    lines.append(f"n_valid_rows: {conditional.get('n_valid_rows')}")
    lines.append(f"n_primary_rows: {conditional.get('n_primary_rows')}")
    lines.append(f"n_positive_lift_rows: {conditional.get('n_positive_lift_rows')}")
    lines.append(f"n_primary_positive_lift_rows: {conditional.get('n_primary_positive_lift_rows')}")
    lines.append(f"n_exploratory_lift_rows: {conditional.get('n_exploratory_lift_rows')}")
    lines.append(f"n_strong_candidate_rows: {conditional.get('n_strong_candidate_rows')}")
    lines.append(f"n_primary_strong_candidate_rows: {conditional.get('n_primary_strong_candidate_rows')}")
    lines.append(f"n_high_epsilon_zero_lift_rows: {conditional.get('n_high_epsilon_zero_lift_rows')}")
    lines.append(f"n_single_channel_rows: {conditional.get('n_single_channel_rows')}")
    lines.append(f"n_single_channel_positive_lift_rows: {conditional.get('n_single_channel_positive_lift_rows')}")
    lines.append(f"n_multichannel_rows: {conditional.get('n_multichannel_rows')}")
    lines.append(f"n_multichannel_positive_lift_rows: {conditional.get('n_multichannel_positive_lift_rows')}")
    lines.append(f"n_multichannel_strong_candidate_rows: {conditional.get('n_multichannel_strong_candidate_rows')}")
    lines.append(f"max_conditional_lift: {conditional.get('max_conditional_lift')}")
    lines.append(f"max_augmented_eps_test: {conditional.get('max_augmented_eps_test')}")
    lines.append(f"max_fraction_positive_lift: {conditional.get('max_fraction_positive_lift')}")
    lines.append(f"best_bic_improvement: {conditional.get('best_bic_improvement')}")
    lines.append(f"best_ll_improvement: {conditional.get('best_ll_improvement')}")
    lines.append(f"max_multichannel_conditional_lift: {conditional.get('max_multichannel_conditional_lift')}")
    lines.append(f"max_multichannel_augmented_eps_test: {conditional.get('max_multichannel_augmented_eps_test')}")
    lines.append(f"max_multichannel_fraction_positive_lift: {conditional.get('max_multichannel_fraction_positive_lift')}")
    lines.append(f"best_multichannel_bic_improvement: {conditional.get('best_multichannel_bic_improvement')}")
    lines.append(f"best_multichannel_ll_improvement: {conditional.get('best_multichannel_ll_improvement')}")
    lines.append(f"interpretation: {conditional.get('interpretation')}")
    lines.append("")

    phase3_2d = report.get("phase3_2d_multichannel_diagnostics", {})
    lines.append("Phase III.2D multichannel diagnostics")
    lines.append("-" * 78)
    lines.append(f"enabled_in_config: {phase3_2d.get('enabled_in_config')}")
    lines.append(f"n_multichannel_rows: {phase3_2d.get('n_multichannel_rows')}")
    lines.append(f"n_multichannel_positive_lift_rows: {phase3_2d.get('n_multichannel_positive_lift_rows')}")
    lines.append(f"n_multichannel_strong_candidate_rows: {phase3_2d.get('n_multichannel_strong_candidate_rows')}")
    lines.append(f"max_multichannel_conditional_lift: {phase3_2d.get('max_multichannel_conditional_lift')}")
    lines.append(f"max_multichannel_augmented_eps_test: {phase3_2d.get('max_multichannel_augmented_eps_test')}")
    lines.append(f"max_multichannel_fraction_positive_lift: {phase3_2d.get('max_multichannel_fraction_positive_lift')}")
    lines.append(f"best_multichannel_bic_improvement: {phase3_2d.get('best_multichannel_bic_improvement')}")
    lines.append(f"best_multichannel_ll_improvement: {phase3_2d.get('best_multichannel_ll_improvement')}")
    lines.append(f"artifact_summary: {phase3_2d.get('artifact_summary')}")
    lines.append(f"control_summary: {phase3_2d.get('control_summary')}")
    lines.append(f"interpretation: {phase3_2d.get('interpretation')}")
    lines.append("")

    pair_sat = conditional.get("pair_saturation", {})
    model_sat = conditional.get("model_saturation", {})
    mc_sat = conditional.get("multichannel_pair_saturation", {})

    lines.append("Epsilon saturation")
    lines.append("-" * 78)
    lines.append(f"pair_saturation: {pair_sat}")
    lines.append(f"multichannel_pair_saturation: {mc_sat}")
    lines.append(f"model_saturation: {model_sat}")
    lines.append("")

    controls = report.get("control_diagnostics", {})
    lines.append("Control diagnostics")
    lines.append("-" * 78)
    lines.append(f"available: {controls.get('available')}")
    lines.append(f"n_control_types: {controls.get('n_control_types')}")
    lines.append(f"n_failed_control_types: {controls.get('n_failed_control_types')}")
    lines.append(f"failed_control_types: {controls.get('failed_control_types')}")
    lines.append(f"total_multichannel_pair_rows: {controls.get('total_multichannel_pair_rows')}")
    lines.append(f"total_multichannel_positive_lift_rows: {controls.get('total_multichannel_positive_lift_rows')}")
    lines.append(f"total_multichannel_strong_candidate_rows: {controls.get('total_multichannel_strong_candidate_rows')}")
    lines.append(f"interpretation: {controls.get('interpretation')}")
    lines.append("")

    gates = report.get("gates_diagnostics", {})
    lines.append("Gates")
    lines.append("-" * 78)
    lines.append(f"passed_gates: {gates.get('passed_gates')}")
    lines.append(f"failed_gates: {gates.get('failed_gates')}")
    lines.append(f"not_evaluated_gates: {gates.get('not_evaluated_gates')}")
    lines.append(f"warning_gates: {gates.get('warning_gates')}")
    lines.append("")

    mc = report.get("multiple_comparison_guard", {})
    lines.append("Multiple-comparison guard")
    lines.append("-" * 78)
    lines.append(f"enabled: {mc.get('enabled')}")
    lines.append(f"n_valid_tests: {mc.get('n_valid_tests')}")
    lines.append(f"n_positive_lift_tests: {mc.get('n_positive_lift_tests')}")
    lines.append(f"n_primary_positive_lift_tests: {mc.get('n_primary_positive_lift_tests')}")
    lines.append(f"n_exploratory_lift_tests: {mc.get('n_exploratory_lift_tests')}")
    lines.append(f"n_strong_candidate_tests: {mc.get('n_strong_candidate_tests')}")
    lines.append(f"n_primary_strong_candidate_tests: {mc.get('n_primary_strong_candidate_tests')}")
    lines.append("")

    lines.append("=" * 78)

    return "\n".join(lines)


# =========================================================
# Main diagnostics
# =========================================================

def run_phase3_2_diagnostics(cfg: Optional[Phase32Config] = None) -> Dict[str, Any]:
    if cfg is None:
        cfg = load_phase3_2_config()

    paths = phase3_2_paths(cfg)
    diagnostics_dir = paths["diagnostics_dir"]
    diagnostics_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 78)
    print("CDR Phase III.2 — Diagnostics")
    print("Leakage-safe conditional estimator aware version")
    print("Phase III.2D multichannel-aware")
    print("=" * 78)

    runner_report = load_json(paths["runner_report"])
    gates_json = load_json(paths["gates_json"])
    mc_guard = load_json(paths["mc_guard"])
    controls_json = load_json(paths["controls_json"])
    loader_metadata = load_json(paths["loader_metadata"])

    multichannel_summary_json = load_json(paths["multichannel_summary"])
    multichannel_inventory_json = load_json(paths["multichannel_inventory"])

    pair_df = load_csv(paths["conditional_pair_scores"])
    model_df = load_csv(paths["conditional_model_scores"])
    multichannel_results_df = load_csv(paths["multichannel_results"])
    multichannel_features_df = load_csv(paths["multichannel_features"])

    control_runs_df = load_csv(paths["control_runs"])
    control_pair_df = load_csv(paths["control_pair_scores"])
    metrics_table_df = load_csv(paths["metrics_table"])
    regime_df = load_csv(paths["regime_inventory"])
    lag_df = load_csv(paths["lag_inventory"])

    print(f"[Diagnostics] conditional pair rows: {len(pair_df)}")
    print(f"[Diagnostics] conditional model rows: {len(model_df)}")
    print(f"[Diagnostics] multichannel result rows: {len(multichannel_results_df)}")
    print(f"[Diagnostics] multichannel feature rows: {len(multichannel_features_df)}")
    print(f"[Diagnostics] control run rows: {len(control_runs_df)}")
    print(f"[Diagnostics] control pair rows: {len(control_pair_df)}")
    print(f"[Diagnostics] regime rows: {len(regime_df)}")
    print(f"[Diagnostics] lag rows: {len(lag_df)}")

    conditional_summary = summarize_conditional(pair_df, model_df, cfg)
    control_summary = summarize_control_runs(control_runs_df, cfg)
    controls_json_summary = summarize_controls_json(controls_json)
    gates_summary = summarize_gates(gates_json, metrics_table_df)
    inventory_summary = summarize_regime_and_lag_inventory(regime_df, lag_df)

    multichannel_summary = summarize_phase3_2d_multichannel(
        pair_df=pair_df,
        model_df=model_df,
        control_pair_df=control_pair_df,
        control_runs_df=control_runs_df,
        multichannel_results_df=multichannel_results_df,
        multichannel_summary_json=multichannel_summary_json,
        multichannel_inventory_json=multichannel_inventory_json,
        multichannel_features_df=multichannel_features_df,
        cfg=cfg,
    )

    final_interpretation = build_final_diagnostic_interpretation(
        conditional_summary=conditional_summary,
        controls_summary=control_summary,
        gates_summary=gates_summary,
        multichannel_summary=multichannel_summary,
        cfg=cfg,
    )

    best_rows = best_rows_by_metric(pair_df)
    best_multichannel_rows = best_multichannel_rows_by_metric(pair_df)

    primary_rows = primary_pair_rows(pair_df)
    positive_rows = positive_lift_rows(pair_df)
    exploratory_rows = exploratory_lift_rows(pair_df, cfg)
    strong_rows = strong_candidate_rows(pair_df, cfg)
    high_eps_zero_lift = high_epsilon_zero_lift_rows(pair_df, cfg)

    single_channel_rows_df = single_channel_pair_rows(pair_df)
    single_channel_positive_rows = single_channel_positive_lift_rows(pair_df)
    multichannel_rows_df = multichannel_pair_rows(pair_df)
    multichannel_positive_rows = multichannel_positive_lift_rows(pair_df)
    multichannel_strong_rows = multichannel_strong_candidate_rows(pair_df, cfg)

    if not control_pair_df.empty:
        multichannel_control_pair_rows = control_pair_df[is_multichannel_pair_mask(control_pair_df)].copy()
    else:
        multichannel_control_pair_rows = pd.DataFrame()

    control_breakdown = pd.DataFrame(control_summary.get("control_breakdown", []))

    report: Dict[str, Any] = {
        "phase": cfg.phase_name,
        "project_name": cfg.project_name,
        "diagnostics_version": "phase3_2_diagnostics_v3_phase3_2d_multichannel_aware",
        "source_files": {k: str(v) for k, v in paths.items() if k != "diagnostics_dir"},
        "runner_final_status": runner_report.get("final_status", {}),
        "loader_metadata_summary": {
            "n_subjects_loaded": loader_metadata.get("n_subjects_loaded"),
            "subjects_loaded": loader_metadata.get("subjects_loaded"),
            "total_rows": loader_metadata.get("total_rows"),
            "rng_bit_count": loader_metadata.get("rng_bit_count"),
            "multichannel_loader_available": loader_metadata.get("multichannel_loader_available"),
            "has_secondary_channel_rows": loader_metadata.get("has_secondary_channel_rows"),
            "secondary_channel_subjects": loader_metadata.get("secondary_channel_subjects"),
        },
        "conditional_diagnostics": conditional_summary,
        "phase3_2d_multichannel_diagnostics": multichannel_summary,
        "control_diagnostics": control_summary,
        "controls_json_summary": controls_json_summary,
        "gates_diagnostics": gates_summary,
        "regime_lag_inventory": inventory_summary,
        "multiple_comparison_guard": mc_guard,
        "final_interpretation": final_interpretation,
    }

    # -----------------------------------------------------
    # Save diagnostic artifacts
    # -----------------------------------------------------
    report_json = diagnostics_dir / "phase3_2_diagnostics_report.json"
    summary_txt = diagnostics_dir / "phase3_2_diagnostics_summary.txt"

    primary_csv = diagnostics_dir / "phase3_2_primary_tests.csv"
    best_csv = diagnostics_dir / "phase3_2_best_rows.csv"
    positive_csv = diagnostics_dir / "phase3_2_positive_lift_rows.csv"
    exploratory_csv = diagnostics_dir / "phase3_2_exploratory_lift_rows.csv"
    strong_csv = diagnostics_dir / "phase3_2_strong_candidate_rows.csv"
    high_eps_csv = diagnostics_dir / "phase3_2_high_epsilon_zero_lift_rows.csv"

    single_channel_csv = diagnostics_dir / "phase3_2c_single_channel_rows.csv"
    single_channel_positive_csv = diagnostics_dir / "phase3_2c_single_channel_positive_lift_rows.csv"

    multichannel_csv = diagnostics_dir / "phase3_2d_multichannel_rows.csv"
    multichannel_positive_csv = diagnostics_dir / "phase3_2d_multichannel_positive_lift_rows.csv"
    multichannel_strong_csv = diagnostics_dir / "phase3_2d_multichannel_strong_candidate_rows.csv"
    multichannel_best_csv = diagnostics_dir / "phase3_2d_multichannel_best_rows.csv"

    control_breakdown_csv = diagnostics_dir / "phase3_2_control_breakdown.csv"
    control_pair_csv = diagnostics_dir / "phase3_2_control_pair_scores_copy.csv"
    multichannel_control_pair_csv = diagnostics_dir / "phase3_2d_control_pair_scores.csv"

    gates_csv = diagnostics_dir / "phase3_2_gates_copy.csv"

    save_json(report_json, report)

    with open(summary_txt, "w", encoding="utf-8") as f:
        f.write(build_diagnostics_summary_text(report))

    primary_rows.to_csv(primary_csv, index=False)
    best_rows.to_csv(best_csv, index=False)
    positive_rows.to_csv(positive_csv, index=False)
    exploratory_rows.to_csv(exploratory_csv, index=False)
    strong_rows.to_csv(strong_csv, index=False)
    high_eps_zero_lift.to_csv(high_eps_csv, index=False)

    single_channel_rows_df.to_csv(single_channel_csv, index=False)
    single_channel_positive_rows.to_csv(single_channel_positive_csv, index=False)

    multichannel_rows_df.to_csv(multichannel_csv, index=False)
    multichannel_positive_rows.to_csv(multichannel_positive_csv, index=False)
    multichannel_strong_rows.to_csv(multichannel_strong_csv, index=False)
    best_multichannel_rows.to_csv(multichannel_best_csv, index=False)

    control_breakdown.to_csv(control_breakdown_csv, index=False)
    control_pair_df.to_csv(control_pair_csv, index=False)
    multichannel_control_pair_rows.to_csv(multichannel_control_pair_csv, index=False)

    metrics_table_df.to_csv(gates_csv, index=False)

    print("\n" + "=" * 78)
    print("Phase III.2 diagnostics completed")
    print("Phase III.2D multichannel-aware")
    print("=" * 78)
    print(f"diagnostics report: {report_json}")
    print(f"diagnostics summary: {summary_txt}")
    print(f"primary tests: {primary_csv}")
    print(f"best rows: {best_csv}")
    print(f"positive lift rows: {positive_csv}")
    print(f"single-channel rows: {single_channel_csv}")
    print(f"multichannel rows: {multichannel_csv}")
    print(f"multichannel positive lift rows: {multichannel_positive_csv}")
    print(f"multichannel strong candidate rows: {multichannel_strong_csv}")
    print(f"multichannel best rows: {multichannel_best_csv}")
    print(f"control breakdown: {control_breakdown_csv}")
    print(f"multichannel control pair rows: {multichannel_control_pair_csv}")
    print("=" * 78 + "\n")

    return report


def main() -> None:
    cfg = load_phase3_2_config()
    report = run_phase3_2_diagnostics(cfg)

    final = report.get("final_interpretation", {})
    phase3_2d = report.get("phase3_2d_multichannel_diagnostics", {})

    print("Final diagnostic headline:")
    print(final.get("headline"))
    print("")
    print("Phase III.2D summary:")
    print(f"multichannel positive lift rows: {phase3_2d.get('n_multichannel_positive_lift_rows')}")
    print(f"multichannel strong candidate rows: {phase3_2d.get('n_multichannel_strong_candidate_rows')}")
    print(f"max multichannel lift: {phase3_2d.get('max_multichannel_conditional_lift')}")
    print(f"best multichannel BIC improvement: {phase3_2d.get('best_multichannel_bic_improvement')}")
    print("")
    print("Recommendation:")
    print(final.get("recommendation"))


if __name__ == "__main__":
    main()