from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

import numpy as np
import pandas as pd

from config.phase3_2_config import Phase32Config, load_phase3_2_config


# =========================================================
# Phase III.2 — Diagnostics
# Leakage-safe conditional estimator aware version
# =========================================================
#
# Purpose:
#
#   Post-run diagnostic audit for Phase III.2 after the leakage-safe
#   conditional estimator patch.
#
# This module does not rerun the experiment.
# It reads outputs generated by:
#
#   python -m src.phase3_2_conditional
#   python -m src.phase3_2_controls
#   python -m src.phase3_2_metrics
#
# It diagnoses:
#
#   - primary vs exploratory results
#   - conditional lift behavior
#   - ε saturation
#   - BIC / complexity behavior
#   - controls collapse under the leakage-safe criteria
#   - failed gates
#   - multiple-comparison guard
#   - final scientific interpretation


# =========================================================
# Generic helpers
# =========================================================

def _json_default(obj: Any) -> Any:
    if isinstance(obj, Path):
        return str(obj)

    if isinstance(obj, (np.integer,)):
        return int(obj)

    if isinstance(obj, (np.floating,)):
        return float(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    if hasattr(obj, "__dict__"):
        return obj.__dict__

    return str(obj)


def save_json(path: Path, payload: Dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False, default=_json_default)


def load_json(path: Path) -> Dict[str, Any]:
    path = Path(path)

    if not path.exists():
        return {}

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_csv(path: Path) -> pd.DataFrame:
    path = Path(path)

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default

        x = float(value)

        if not np.isfinite(x):
            return default

        return x

    except Exception:
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if pd.isna(value):
            return default

        return int(value)

    except Exception:
        return default


def _as_bool_series(series: pd.Series) -> pd.Series:
    if series.empty:
        return pd.Series([], dtype=bool)

    if series.dtype == bool:
        return series

    return series.astype(str).str.lower().isin(["true", "1", "yes"])


def _safe_records(df: pd.DataFrame) -> List[Dict[str, Any]]:
    if df.empty:
        return []

    return df.replace({np.nan: None}).to_dict(orient="records")


def _select_existing_columns(df: pd.DataFrame, columns: List[str]) -> List[str]:
    return [c for c in columns if c in df.columns]


def _numeric_series(df: pd.DataFrame, col: str, default: float = 0.0) -> pd.Series:
    if df.empty:
        return pd.Series([], dtype=float)

    if col not in df.columns:
        return pd.Series([default] * len(df), index=df.index, dtype=float)

    return pd.to_numeric(df[col], errors="coerce").fillna(default)


def _cfg_float(cfg: Phase32Config, name: str, default: float) -> float:
    return float(getattr(cfg, name, default))


# =========================================================
# Paths
# =========================================================

def phase3_2_paths(cfg: Phase32Config) -> Dict[str, Path]:
    results_dir = Path(cfg.results_dir)
    interim_dir = Path(cfg.interim_dir)
    diagnostics_dir = Path(cfg.diagnostics_dir)

    return {
        "runner_report": results_dir / "phase3_2_runner_report.json",
        "runner_summary": results_dir / "phase3_2_runner_summary.txt",
        "gates_json": Path(cfg.gates_json),
        "metrics_table": results_dir / "phase3_2_metrics_table.csv",
        "metrics_summary": results_dir / "phase3_2_metrics_summary.txt",
        "mc_guard": Path(cfg.multiple_comparison_guard_json),
        "conditional_pair_scores": Path(cfg.conditional_results_csv),
        "conditional_model_scores": results_dir / "phase3_2c_conditional_model_scores.csv",
        "conditional_summary": Path(cfg.conditional_summary_json),
        "control_runs": results_dir / "phase3_2_control_runs.csv",
        "control_pair_scores": results_dir / "phase3_2_control_pair_scores.csv",
        "controls_json": Path(cfg.controls_json),
        "regime_inventory": interim_dir / "phase3_2_regime_inventory.csv",
        "lag_inventory": interim_dir / "phase3_2_lag_inventory.csv",
        "feature_specs": interim_dir / "phase3_2_feature_specs.json",
        "loader_metadata": Path(cfg.loader_metadata_file),
        "diagnostics_dir": diagnostics_dir,
    }


# =========================================================
# Conditional row selectors
# =========================================================

def valid_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    if pair_df.empty or "valid" not in pair_df.columns:
        return pd.DataFrame()

    return pair_df[_as_bool_series(pair_df["valid"])].copy()


def primary_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty or "primary" not in valid.columns:
        return pd.DataFrame()

    return valid[_as_bool_series(valid["primary"])].copy()


def positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    lift = _numeric_series(valid, "conditional_lift")
    return valid[lift > 0.0].copy()


def primary_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    primary = primary_pair_rows(pair_df)

    if primary.empty:
        return pd.DataFrame()

    lift = _numeric_series(primary, "conditional_lift")
    return primary[lift > 0.0].copy()


def strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    lift = _numeric_series(valid, "conditional_lift")
    eps = _numeric_series(valid, "augmented_eps_test")
    frac = _numeric_series(valid, "fraction_positive_lift")
    bic = _numeric_series(valid, "bic_improvement")

    strong = valid[
        (lift >= float(cfg.conditional_lift_min))
        & (eps >= float(cfg.strong_eps_min))
        & (frac >= float(cfg.subject_effect_fraction))
        & (bic >= 0.0)
    ].copy()

    return strong


def primary_strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty or "primary" not in strong.columns:
        return pd.DataFrame()

    return strong[_as_bool_series(strong["primary"])].copy()


def exploratory_lift_rows(pair_df: pd.DataFrame, cfg: Phase32Config) -> pd.DataFrame:
    positive = positive_lift_rows(pair_df)

    if positive.empty:
        return pd.DataFrame()

    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty:
        return positive.copy()

    return positive[~positive.index.isin(set(strong.index.tolist()))].copy()


def high_epsilon_zero_lift_rows(
    pair_df: pd.DataFrame,
    cfg: Phase32Config,
) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    eps_threshold = _cfg_float(cfg, "eps_saturation_value", 0.80)

    eps = _numeric_series(valid, "augmented_eps_test")
    lift = _numeric_series(valid, "conditional_lift")

    return valid[(eps >= eps_threshold) & (lift <= 0.0)].copy()


def best_rows_by_metric(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    metrics = [
        ("conditional_lift", True),
        ("augmented_eps_test", True),
        ("baseline_eps_test", True),
        ("ll_improvement", True),
        ("bic_improvement", True),
        ("aic_improvement", True),
        ("fraction_positive_lift", True),
    ]

    rows: List[Dict[str, Any]] = []

    for metric, descending in metrics:
        if metric not in valid.columns:
            continue

        sorted_df = valid.sort_values(metric, ascending=not descending).reset_index(drop=True)

        if sorted_df.empty:
            continue

        row = sorted_df.iloc[0].to_dict()
        row["selected_by"] = metric
        rows.append(row)

    if not rows:
        return pd.DataFrame()

    best_df = pd.DataFrame(rows)

    preferred_columns = [
        "selected_by",
        "regime",
        "lag_epochs",
        "lag_label",
        "family",
        "baseline_model",
        "augmented_model",
        "primary",
        "valid",
        "baseline_eps_test",
        "augmented_eps_test",
        "conditional_lift",
        "fraction_positive_lift",
        "ll_improvement",
        "bic_improvement",
        "aic_improvement",
        "n_subjects_evaluated",
        "n_subjects_positive_lift",
        "reason",
    ]

    cols = _select_existing_columns(best_df, preferred_columns)
    return best_df[cols].copy()


# =========================================================
# Saturation diagnostics
# =========================================================

def summarize_model_saturation(
    model_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    if model_df.empty:
        return {
            "available": False,
            "reason": "model_scores_missing",
        }

    eps_saturation_value = _cfg_float(cfg, "eps_saturation_value", 0.80)

    eps_cols = [
        col for col in ["eps_candidate", "eps_calib", "eps_test"]
        if col in model_df.columns
    ]

    if not eps_cols:
        return {
            "available": False,
            "reason": "no_epsilon_columns_available",
        }

    summary: Dict[str, Any] = {
        "available": True,
        "eps_saturation_value": eps_saturation_value,
        "n_model_rows": int(len(model_df)),
        "columns": {},
    }

    for col in eps_cols:
        values = _numeric_series(model_df, col)
        saturated = values >= eps_saturation_value

        summary["columns"][col] = {
            "max": float(values.max()) if len(values) else 0.0,
            "mean": float(values.mean()) if len(values) else 0.0,
            "n_saturated": int(saturated.sum()),
            "saturation_fraction": float(np.mean(saturated.to_numpy(dtype=bool))) if len(saturated) else 0.0,
        }

    if "eps_saturated" in model_df.columns:
        explicit = _as_bool_series(model_df["eps_saturated"])
        summary["explicit_eps_saturated"] = {
            "n_saturated": int(explicit.sum()),
            "saturation_fraction": float(np.mean(explicit.to_numpy(dtype=bool))) if len(explicit) else 0.0,
        }

    max_fraction = max(
        item.get("saturation_fraction", 0.0)
        for item in summary["columns"].values()
    )

    warning_fraction = _cfg_float(cfg, "eps_saturation_warning_fraction", 0.50)

    summary["max_saturation_fraction"] = float(max_fraction)
    summary["warning_fraction"] = float(warning_fraction)
    summary["warning"] = bool(max_fraction >= warning_fraction)
    summary["reason"] = "epsilon_saturation_warning" if summary["warning"] else "ok"

    return summary


def summarize_pair_saturation(
    pair_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return {
            "available": False,
            "reason": "no_valid_pair_rows",
        }

    eps_saturation_value = _cfg_float(cfg, "eps_saturation_value", 0.80)
    warning_fraction = _cfg_float(cfg, "eps_saturation_warning_fraction", 0.50)

    baseline_eps = _numeric_series(valid, "baseline_eps_test")
    augmented_eps = _numeric_series(valid, "augmented_eps_test")

    baseline_sat = baseline_eps >= eps_saturation_value
    augmented_sat = augmented_eps >= eps_saturation_value
    either_sat = baseline_sat | augmented_sat
    both_sat = baseline_sat & augmented_sat

    either_fraction = float(np.mean(either_sat.to_numpy(dtype=bool))) if len(either_sat) else 0.0
    both_fraction = float(np.mean(both_sat.to_numpy(dtype=bool))) if len(both_sat) else 0.0

    return {
        "available": True,
        "eps_saturation_value": float(eps_saturation_value),
        "warning_fraction": float(warning_fraction),
        "n_valid_pair_rows": int(len(valid)),
        "max_baseline_eps_test": float(baseline_eps.max()) if len(baseline_eps) else 0.0,
        "max_augmented_eps_test": float(augmented_eps.max()) if len(augmented_eps) else 0.0,
        "n_either_saturated": int(either_sat.sum()),
        "n_both_saturated": int(both_sat.sum()),
        "either_saturation_fraction": either_fraction,
        "both_saturation_fraction": both_fraction,
        "warning": bool(either_fraction >= warning_fraction),
        "reason": "pair_level_epsilon_saturation_warning" if either_fraction >= warning_fraction else "ok",
    }


# =========================================================
# Conditional diagnostics
# =========================================================

def summarize_conditional(
    pair_df: pd.DataFrame,
    model_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)
    primary = primary_pair_rows(pair_df)
    positive = positive_lift_rows(pair_df)
    primary_positive = primary_positive_lift_rows(pair_df)
    strong = strong_candidate_rows(pair_df, cfg)
    primary_strong = primary_strong_candidate_rows(pair_df, cfg)
    exploratory = exploratory_lift_rows(pair_df, cfg)
    high_eps_zero_lift = high_epsilon_zero_lift_rows(pair_df, cfg)

    summary: Dict[str, Any] = {
        "available": not pair_df.empty,
        "n_rows": int(len(pair_df)),
        "n_valid_rows": int(len(valid)),
        "n_primary_rows": int(len(primary)),
        "n_positive_lift_rows": int(len(positive)),
        "n_primary_positive_lift_rows": int(len(primary_positive)),
        "n_exploratory_lift_rows": int(len(exploratory)),
        "n_strong_candidate_rows": int(len(strong)),
        "n_primary_strong_candidate_rows": int(len(primary_strong)),
        "n_high_epsilon_zero_lift_rows": int(len(high_eps_zero_lift)),
        "thresholds": {
            "conditional_lift_min": float(cfg.conditional_lift_min),
            "strong_eps_min": float(cfg.strong_eps_min),
            "subject_effect_fraction": float(cfg.subject_effect_fraction),
            "eps_saturation_value": _cfg_float(cfg, "eps_saturation_value", 0.80),
        },
        "model_saturation": summarize_model_saturation(model_df, cfg),
        "pair_saturation": summarize_pair_saturation(pair_df, cfg),
        "interpretation": "",
    }

    if valid.empty:
        summary["interpretation"] = "No valid conditional rows were available."
        return summary

    lift = _numeric_series(valid, "conditional_lift")
    eps = _numeric_series(valid, "augmented_eps_test")
    frac = _numeric_series(valid, "fraction_positive_lift")
    bic = _numeric_series(valid, "bic_improvement")
    ll = _numeric_series(valid, "ll_improvement")

    summary.update(
        {
            "max_conditional_lift": float(lift.max()) if len(lift) else 0.0,
            "max_augmented_eps_test": float(eps.max()) if len(eps) else 0.0,
            "max_fraction_positive_lift": float(frac.max()) if len(frac) else 0.0,
            "best_bic_improvement": float(bic.max()) if len(bic) else 0.0,
            "best_ll_improvement": float(ll.max()) if len(ll) else 0.0,
            "primary_rows": _safe_records(primary),
            "positive_lift_rows": _safe_records(positive),
            "primary_positive_lift_rows": _safe_records(primary_positive),
            "exploratory_lift_rows": _safe_records(exploratory),
            "strong_candidate_rows": _safe_records(strong),
            "primary_strong_candidate_rows": _safe_records(primary_strong),
            "high_epsilon_zero_lift_rows": _safe_records(high_eps_zero_lift),
        }
    )

    if len(primary_strong) > 0:
        summary["interpretation"] = (
            "At least one primary strong candidate row exists before final replication review."
        )
    elif len(strong) > 0:
        summary["interpretation"] = (
            "Strong candidate rows exist only outside the primary registered structure."
        )
    elif len(positive) > 0:
        summary["interpretation"] = (
            "Positive conditional lift rows exist, but they remain exploratory because they "
            "do not satisfy all registered criteria simultaneously."
        )
    else:
        summary["interpretation"] = (
            "No positive conditional lift rows were detected."
        )

    return summary


# =========================================================
# Control diagnostics
# =========================================================

def summarize_control_runs(
    control_runs_df: pd.DataFrame,
    cfg: Phase32Config,
) -> Dict[str, Any]:
    if control_runs_df.empty:
        return {
            "available": False,
            "reason": "control_runs_missing",
            "interpretation": "No control run CSV was found.",
        }

    rows: List[Dict[str, Any]] = []

    for control_type, group in control_runs_df.groupby("control_type", sort=True):
        valid = group[_as_bool_series(group["valid"])] if "valid" in group.columns else group.copy()

        if valid.empty:
            rows.append(
                {
                    "control_type": str(control_type),
                    "n_runs": int(len(group)),
                    "n_valid_runs": 0,
                    "median_max_baseline_eps_test": 0.0,
                    "median_max_augmented_eps_test": 0.0,
                    "max_augmented_eps_test": 0.0,
                    "median_max_lift": 0.0,
                    "max_lift": 0.0,
                    "median_max_bic_improvement": 0.0,
                    "max_bic_improvement": 0.0,
                    "median_eps_saturation_fraction": 0.0,
                    "max_eps_saturation_fraction": 0.0,
                    "fraction_collapsed_overall": 0.0,
                    "passed_estimate": False,
                    "reason": "no_valid_runs",
                }
            )
            continue

        baseline_eps = _numeric_series(valid, "max_baseline_eps_test")
        augmented_eps = _numeric_series(valid, "max_augmented_eps_test")
        max_lift = _numeric_series(valid, "max_conditional_lift")
        max_bic = _numeric_series(valid, "max_bic_improvement")
        sat_frac = _numeric_series(valid, "eps_saturation_fraction")

        if "collapsed_overall" in valid.columns:
            collapsed = _as_bool_series(valid["collapsed_overall"])
        else:
            frac = _numeric_series(valid, "max_fraction_positive_lift")
            n_strong = _numeric_series(valid, "n_strong_candidate_rows")
            collapsed = (
                (max_lift <= float(cfg.control_tol))
                & (max_bic <= 0.0)
                & (frac < float(cfg.subject_effect_fraction))
                & (n_strong.astype(int) == 0)
            )

        fraction_collapsed = float(np.mean(collapsed.to_numpy(dtype=bool))) if len(collapsed) else 0.0
        passed_estimate = fraction_collapsed >= float(cfg.required_control_fraction)

        rows.append(
            {
                "control_type": str(control_type),
                "n_runs": int(len(group)),
                "n_valid_runs": int(len(valid)),
                "median_max_baseline_eps_test": float(baseline_eps.median()) if len(baseline_eps) else 0.0,
                "median_max_augmented_eps_test": float(augmented_eps.median()) if len(augmented_eps) else 0.0,
                "mean_max_augmented_eps_test": float(augmented_eps.mean()) if len(augmented_eps) else 0.0,
                "max_augmented_eps_test": float(augmented_eps.max()) if len(augmented_eps) else 0.0,
                "median_max_lift": float(max_lift.median()) if len(max_lift) else 0.0,
                "mean_max_lift": float(max_lift.mean()) if len(max_lift) else 0.0,
                "max_lift": float(max_lift.max()) if len(max_lift) else 0.0,
                "median_max_bic_improvement": float(max_bic.median()) if len(max_bic) else 0.0,
                "max_bic_improvement": float(max_bic.max()) if len(max_bic) else 0.0,
                "median_eps_saturation_fraction": float(sat_frac.median()) if len(sat_frac) else 0.0,
                "max_eps_saturation_fraction": float(sat_frac.max()) if len(sat_frac) else 0.0,
                "fraction_collapsed_overall": fraction_collapsed,
                "required_control_fraction": float(cfg.required_control_fraction),
                "control_tol": float(cfg.control_tol),
                "passed_estimate": bool(passed_estimate),
                "reason": "ok" if passed_estimate else "control_effect_survived",
            }
        )

    breakdown = pd.DataFrame(rows)
    failed = breakdown[breakdown["passed_estimate"] == False].copy()

    return {
        "available": True,
        "n_control_types": int(len(breakdown)),
        "n_failed_control_types": int(len(failed)),
        "failed_control_types": failed["control_type"].tolist() if not failed.empty else [],
        "control_breakdown": breakdown.to_dict(orient="records"),
        "interpretation": (
            "All control types collapsed under the leakage-safe control criteria."
            if failed.empty
            else "At least one negative control did not collapse under the leakage-safe control criteria."
        ),
    }


def summarize_controls_json(controls_json: Mapping[str, Any]) -> Dict[str, Any]:
    if not controls_json:
        return {
            "available": False,
            "reason": "controls_json_missing",
        }

    summary = controls_json.get("summary", controls_json)

    return {
        "available": True,
        "module": controls_json.get("module"),
        "passed": bool(summary.get("passed", False)),
        "failed_control_types": summary.get("failed_control_types", []),
        "n_control_types": summary.get("n_control_types"),
        "raw_summary": summary,
    }


# =========================================================
# Gates diagnostics
# =========================================================

def summarize_gates(
    gates_json: Mapping[str, Any],
    metrics_table_df: pd.DataFrame,
) -> Dict[str, Any]:
    if gates_json:
        final_status = gates_json.get("final_status", {})
        gates = gates_json.get("gates", [])
        epsilon_saturation = gates_json.get("epsilon_saturation", {})
    else:
        final_status = {}
        gates = metrics_table_df.to_dict(orient="records") if not metrics_table_df.empty else []
        epsilon_saturation = {}

    passed: List[str] = []
    failed: List[str] = []
    not_evaluated: List[str] = []
    warnings: List[str] = []

    for gate in gates:
        status = str(gate.get("status", "")).upper()
        name = str(gate.get("gate", ""))

        if status == "PASS":
            passed.append(name)
        elif status == "FAIL":
            failed.append(name)
        elif status == "NOT_EVALUATED":
            not_evaluated.append(name)
        elif status == "WARN":
            warnings.append(name)

    return {
        "available": bool(gates),
        "final_status": final_status,
        "passed_gates": passed,
        "failed_gates": failed,
        "not_evaluated_gates": not_evaluated,
        "warning_gates": warnings,
        "gates": gates,
        "epsilon_saturation": epsilon_saturation,
    }


# =========================================================
# Regime / lag diagnostics
# =========================================================

def summarize_regime_and_lag_inventory(
    regime_df: pd.DataFrame,
    lag_df: pd.DataFrame,
) -> Dict[str, Any]:
    summary: Dict[str, Any] = {
        "regime_inventory_available": not regime_df.empty,
        "lag_inventory_available": not lag_df.empty,
    }

    if not regime_df.empty:
        valid_col = _as_bool_series(regime_df["valid"]) if "valid" in regime_df.columns else pd.Series([], dtype=bool)

        summary["regimes"] = {
            "n_regimes": int(len(regime_df)),
            "n_valid_regimes": int(valid_col.sum()) if not valid_col.empty else 0,
            "valid_regimes": regime_df.loc[valid_col, "regime"].astype(str).tolist() if "regime" in regime_df.columns and not valid_col.empty else [],
            "rows": _safe_records(regime_df),
        }

    if not lag_df.empty:
        valid_col = _as_bool_series(lag_df["valid"]) if "valid" in lag_df.columns else pd.Series([], dtype=bool)

        summary["lags"] = {
            "n_lagged_frames": int(len(lag_df)),
            "n_valid_lagged_frames": int(valid_col.sum()) if not valid_col.empty else 0,
            "rows": _safe_records(lag_df),
        }

    return summary


# =========================================================
# Final interpretation
# =========================================================

def build_final_diagnostic_interpretation(
    conditional_summary: Mapping[str, Any],
    controls_summary: Mapping[str, Any],
    gates_summary: Mapping[str, Any],
) -> Dict[str, Any]:
    final_status = gates_summary.get("final_status", {})
    status = final_status.get("status", "unknown")

    n_positive = _safe_int(conditional_summary.get("n_positive_lift_rows"))
    n_primary_positive = _safe_int(conditional_summary.get("n_primary_positive_lift_rows"))
    n_strong = _safe_int(conditional_summary.get("n_strong_candidate_rows"))
    n_primary_strong = _safe_int(conditional_summary.get("n_primary_strong_candidate_rows"))

    controls_failed = _safe_int(controls_summary.get("n_failed_control_types")) > 0

    failed_gates = gates_summary.get("failed_gates", [])
    warning_gates = gates_summary.get("warning_gates", [])
    not_eval = gates_summary.get("not_evaluated_gates", [])

    if status == "candidate_signal":
        headline = "Phase III.2 produced a primary candidate signal."
    elif status == "blocked_by_controls":
        headline = "Phase III.2 is blocked by controls."
    elif status == "exploratory_lead_with_saturation_warning":
        headline = "Phase III.2 produced exploratory leads with ε saturation warning."
    elif status == "exploratory_lead_only":
        headline = "Phase III.2 produced exploratory leads only."
    elif status == "conditional_null_result":
        headline = "Phase III.2 produced a clean conditional null result."
    elif status == "pending_controls_exploratory_lead":
        headline = "Phase III.2 has exploratory leads but controls are pending."
    else:
        headline = "Phase III.2 produced a non-confirmatory result."

    scientific_read: List[str] = []

    if n_positive > 0:
        scientific_read.append(
            f"Positive conditional lift rows were detected: {n_positive}. "
            f"Primary positive rows: {n_primary_positive}."
        )
    else:
        scientific_read.append(
            "No positive conditional lift rows were detected."
        )

    if n_strong == 0:
        scientific_read.append(
            "No strong candidate rows satisfied lift, epsilon, subject-consistency and BIC criteria simultaneously."
        )
    else:
        scientific_read.append(
            f"Strong candidate rows detected: {n_strong}. Primary strong candidates: {n_primary_strong}."
        )

    if controls_failed:
        scientific_read.append(
            "At least one negative control did not collapse; strong interpretation is blocked."
        )
    else:
        scientific_read.append(
            "Negative controls collapsed under the leakage-safe criteria."
        )

    if "F7" in failed_gates:
        scientific_read.append(
            "F7 failed: subject-level consistency was insufficient for a strong claim."
        )

    if "F8" in failed_gates:
        scientific_read.append(
            "F8 failed: the augmented conditional model was not favored by BIC."
        )

    if "F12" in warning_gates:
        scientific_read.append(
            "F12 warning: ε saturation remains present and must be treated as a diagnostic limitation."
        )

    if not_eval:
        scientific_read.append(
            f"Not evaluated in this standalone diagnostic run: {not_eval}."
        )

    if status == "exploratory_lead_with_saturation_warning":
        recommendation = (
            "Treat Phase III.2 as an exploratory lead only. Controls passed, but F7/F8 failed and "
            "F12 raised an ε saturation warning. Do not claim EEG-RNG coupling. The appropriate "
            "next step is to document the lead, preserve the null/guardrail interpretation, and "
            "only activate III.2D/III.2E as exploratory extensions or future protocol work."
        )
    elif status == "conditional_null_result":
        recommendation = (
            "Treat Phase III.2 as a clean conditional null result under the current public-data design."
        )
    elif status == "blocked_by_controls":
        recommendation = (
            "Do not proceed to a positive interpretation. Inspect control-level outputs before extending the phase."
        )
    else:
        recommendation = (
            "Treat Phase III.2 as non-confirmatory unless future diagnostics satisfy controls, subject consistency, BIC and saturation criteria."
        )

    return {
        "headline": headline,
        "status": status,
        "scientific_read": scientific_read,
        "recommendation": recommendation,
    }


# =========================================================
# Text report
# =========================================================

def build_diagnostics_summary_text(report: Mapping[str, Any]) -> str:
    lines: List[str] = []

    lines.append("=" * 78)
    lines.append("CDR Phase III.2 — Diagnostics Summary")
    lines.append("Leakage-safe conditional estimator aware version")
    lines.append("=" * 78)
    lines.append("")

    final = report.get("final_interpretation", {})
    lines.append("Final interpretation")
    lines.append("-" * 78)
    lines.append(f"headline: {final.get('headline')}")
    lines.append(f"status: {final.get('status')}")
    lines.append("")

    for item in final.get("scientific_read", []):
        lines.append(f"- {item}")

    lines.append("")
    lines.append(f"recommendation: {final.get('recommendation')}")
    lines.append("")

    conditional = report.get("conditional_diagnostics", {})
    lines.append("Conditional diagnostics")
    lines.append("-" * 78)
    lines.append(f"n_rows: {conditional.get('n_rows')}")
    lines.append(f"n_valid_rows: {conditional.get('n_valid_rows')}")
    lines.append(f"n_primary_rows: {conditional.get('n_primary_rows')}")
    lines.append(f"n_positive_lift_rows: {conditional.get('n_positive_lift_rows')}")
    lines.append(f"n_primary_positive_lift_rows: {conditional.get('n_primary_positive_lift_rows')}")
    lines.append(f"n_exploratory_lift_rows: {conditional.get('n_exploratory_lift_rows')}")
    lines.append(f"n_strong_candidate_rows: {conditional.get('n_strong_candidate_rows')}")
    lines.append(f"n_primary_strong_candidate_rows: {conditional.get('n_primary_strong_candidate_rows')}")
    lines.append(f"n_high_epsilon_zero_lift_rows: {conditional.get('n_high_epsilon_zero_lift_rows')}")
    lines.append(f"max_conditional_lift: {conditional.get('max_conditional_lift')}")
    lines.append(f"max_augmented_eps_test: {conditional.get('max_augmented_eps_test')}")
    lines.append(f"max_fraction_positive_lift: {conditional.get('max_fraction_positive_lift')}")
    lines.append(f"best_bic_improvement: {conditional.get('best_bic_improvement')}")
    lines.append(f"best_ll_improvement: {conditional.get('best_ll_improvement')}")
    lines.append(f"interpretation: {conditional.get('interpretation')}")
    lines.append("")

    pair_sat = conditional.get("pair_saturation", {})
    model_sat = conditional.get("model_saturation", {})

    lines.append("Epsilon saturation")
    lines.append("-" * 78)
    lines.append(f"pair_saturation: {pair_sat}")
    lines.append(f"model_saturation: {model_sat}")
    lines.append("")

    controls = report.get("control_diagnostics", {})
    lines.append("Control diagnostics")
    lines.append("-" * 78)
    lines.append(f"available: {controls.get('available')}")
    lines.append(f"n_control_types: {controls.get('n_control_types')}")
    lines.append(f"n_failed_control_types: {controls.get('n_failed_control_types')}")
    lines.append(f"failed_control_types: {controls.get('failed_control_types')}")
    lines.append(f"interpretation: {controls.get('interpretation')}")
    lines.append("")

    gates = report.get("gates_diagnostics", {})
    lines.append("Gates")
    lines.append("-" * 78)
    lines.append(f"passed_gates: {gates.get('passed_gates')}")
    lines.append(f"failed_gates: {gates.get('failed_gates')}")
    lines.append(f"not_evaluated_gates: {gates.get('not_evaluated_gates')}")
    lines.append(f"warning_gates: {gates.get('warning_gates')}")
    lines.append("")

    mc = report.get("multiple_comparison_guard", {})
    lines.append("Multiple-comparison guard")
    lines.append("-" * 78)
    lines.append(f"enabled: {mc.get('enabled')}")
    lines.append(f"n_valid_tests: {mc.get('n_valid_tests')}")
    lines.append(f"n_positive_lift_tests: {mc.get('n_positive_lift_tests')}")
    lines.append(f"n_primary_positive_lift_tests: {mc.get('n_primary_positive_lift_tests')}")
    lines.append(f"n_exploratory_lift_tests: {mc.get('n_exploratory_lift_tests')}")
    lines.append(f"n_strong_candidate_tests: {mc.get('n_strong_candidate_tests')}")
    lines.append(f"n_primary_strong_candidate_tests: {mc.get('n_primary_strong_candidate_tests')}")
    lines.append("")

    lines.append("=" * 78)

    return "\n".join(lines)


# =========================================================
# Main diagnostics
# =========================================================

def run_phase3_2_diagnostics(cfg: Optional[Phase32Config] = None) -> Dict[str, Any]:
    if cfg is None:
        cfg = load_phase3_2_config()

    paths = phase3_2_paths(cfg)
    diagnostics_dir = paths["diagnostics_dir"]
    diagnostics_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 78)
    print("CDR Phase III.2 — Diagnostics")
    print("Leakage-safe conditional estimator aware version")
    print("=" * 78)

    runner_report = load_json(paths["runner_report"])
    gates_json = load_json(paths["gates_json"])
    mc_guard = load_json(paths["mc_guard"])
    controls_json = load_json(paths["controls_json"])
    loader_metadata = load_json(paths["loader_metadata"])

    pair_df = load_csv(paths["conditional_pair_scores"])
    model_df = load_csv(paths["conditional_model_scores"])
    control_runs_df = load_csv(paths["control_runs"])
    control_pair_df = load_csv(paths["control_pair_scores"])
    metrics_table_df = load_csv(paths["metrics_table"])
    regime_df = load_csv(paths["regime_inventory"])
    lag_df = load_csv(paths["lag_inventory"])

    print(f"[Diagnostics] conditional pair rows: {len(pair_df)}")
    print(f"[Diagnostics] conditional model rows: {len(model_df)}")
    print(f"[Diagnostics] control run rows: {len(control_runs_df)}")
    print(f"[Diagnostics] control pair rows: {len(control_pair_df)}")
    print(f"[Diagnostics] regime rows: {len(regime_df)}")
    print(f"[Diagnostics] lag rows: {len(lag_df)}")

    conditional_summary = summarize_conditional(pair_df, model_df, cfg)
    control_summary = summarize_control_runs(control_runs_df, cfg)
    controls_json_summary = summarize_controls_json(controls_json)
    gates_summary = summarize_gates(gates_json, metrics_table_df)
    inventory_summary = summarize_regime_and_lag_inventory(regime_df, lag_df)

    final_interpretation = build_final_diagnostic_interpretation(
        conditional_summary=conditional_summary,
        controls_summary=control_summary,
        gates_summary=gates_summary,
    )

    best_rows = best_rows_by_metric(pair_df)
    primary_rows = primary_pair_rows(pair_df)
    positive_rows = positive_lift_rows(pair_df)
    exploratory_rows = exploratory_lift_rows(pair_df, cfg)
    strong_rows = strong_candidate_rows(pair_df, cfg)
    high_eps_zero_lift = high_epsilon_zero_lift_rows(pair_df, cfg)
    control_breakdown = pd.DataFrame(control_summary.get("control_breakdown", []))

    report: Dict[str, Any] = {
        "phase": cfg.phase_name,
        "project_name": cfg.project_name,
        "diagnostics_version": "phase3_2_diagnostics_v2_leakage_safe",
        "source_files": {k: str(v) for k, v in paths.items() if k != "diagnostics_dir"},
        "runner_final_status": runner_report.get("final_status", {}),
        "loader_metadata_summary": {
            "n_subjects_loaded": loader_metadata.get("n_subjects_loaded"),
            "subjects_loaded": loader_metadata.get("subjects_loaded"),
            "total_rows": loader_metadata.get("total_rows"),
            "rng_bit_count": loader_metadata.get("rng_bit_count"),
        },
        "conditional_diagnostics": conditional_summary,
        "control_diagnostics": control_summary,
        "controls_json_summary": controls_json_summary,
        "gates_diagnostics": gates_summary,
        "regime_lag_inventory": inventory_summary,
        "multiple_comparison_guard": mc_guard,
        "final_interpretation": final_interpretation,
    }

    # -----------------------------------------------------
    # Save diagnostic artifacts
    # -----------------------------------------------------
    report_json = diagnostics_dir / "phase3_2_diagnostics_report.json"
    summary_txt = diagnostics_dir / "phase3_2_diagnostics_summary.txt"
    primary_csv = diagnostics_dir / "phase3_2_primary_tests.csv"
    best_csv = diagnostics_dir / "phase3_2_best_rows.csv"
    positive_csv = diagnostics_dir / "phase3_2_positive_lift_rows.csv"
    exploratory_csv = diagnostics_dir / "phase3_2_exploratory_lift_rows.csv"
    strong_csv = diagnostics_dir / "phase3_2_strong_candidate_rows.csv"
    high_eps_csv = diagnostics_dir / "phase3_2_high_epsilon_zero_lift_rows.csv"
    control_breakdown_csv = diagnostics_dir / "phase3_2_control_breakdown.csv"
    control_pair_csv = diagnostics_dir / "phase3_2_control_pair_scores_copy.csv"
    gates_csv = diagnostics_dir / "phase3_2_gates_copy.csv"

    save_json(report_json, report)

    with open(summary_txt, "w", encoding="utf-8") as f:
        f.write(build_diagnostics_summary_text(report))

    primary_rows.to_csv(primary_csv, index=False)
    best_rows.to_csv(best_csv, index=False)
    positive_rows.to_csv(positive_csv, index=False)
    exploratory_rows.to_csv(exploratory_csv, index=False)
    strong_rows.to_csv(strong_csv, index=False)
    high_eps_zero_lift.to_csv(high_eps_csv, index=False)
    control_breakdown.to_csv(control_breakdown_csv, index=False)
    control_pair_df.to_csv(control_pair_csv, index=False)
    metrics_table_df.to_csv(gates_csv, index=False)

    print("\n" + "=" * 78)
    print("Phase III.2 diagnostics completed")
    print("=" * 78)
    print(f"diagnostics report: {report_json}")
    print(f"diagnostics summary: {summary_txt}")
    print(f"primary tests: {primary_csv}")
    print(f"best rows: {best_csv}")
    print(f"positive lift rows: {positive_csv}")
    print(f"exploratory lift rows: {exploratory_csv}")
    print(f"strong candidate rows: {strong_csv}")
    print(f"high epsilon / zero lift rows: {high_eps_csv}")
    print(f"control breakdown: {control_breakdown_csv}")
    print("=" * 78 + "\n")

    return report


def main() -> None:
    cfg = load_phase3_2_config()
    report = run_phase3_2_diagnostics(cfg)

    final = report.get("final_interpretation", {})

    print("Final diagnostic headline:")
    print(final.get("headline"))
    print("")
    print("Recommendation:")
    print(final.get("recommendation"))


if __name__ == "__main__":
    main()