from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

import numpy as np
import pandas as pd

from config.phase3_2e_config import Phase32EConfig, describe_config, load_phase3_2e_config


# =========================================================
# Phase III.2E — Diagnostics
# Synchronized EEG–QRNG protocol and gate-sensitivity version
# =========================================================
#
# Purpose:
#
#   Post-run diagnostic audit for Phase III.2E.
#
# This module does not rerun the experiment.
# It reads outputs generated by:
#
#   python -m config.phase3_2e_config
#   python -m src.phase3_2e_schema
#   python -m src.phase3_2e_sync_validator
#   python -m src.phase3_2e_loader
#   python -m src.phase3_2e_windows
#   python -m src.phase3_2e_features
#   python -m src.phase3_2e_alignment
#   python -m src.phase3_2e_conditional
#   python -m src.phase3_2e_controls
#   python -m src.phase3_2e_metrics
#   python -m src.phase3_2e_gate_sensitivity
#
# It diagnoses:
#
#   - protocol-only vs empirical execution state
#   - schema/synchronization readiness
#   - loader/window/feature/alignment readiness
#   - conditional EEG–QRNG rows
#   - multichannel synchronized rows
#   - controls availability/pass state
#   - official gates
#   - F7/F8/F12 gate-sensitivity diagnostics
#   - final scientific interpretation
#
# Important:
#
#   III.2E requires real synchronized EEG + QRNG acquisition timestamps.
#   If no synchronized dataset exists, protocol-only outputs are valid, but
#   no empirical CDR claim is allowed.
#


# =========================================================
# Constants
# =========================================================

DIAGNOSTICS_MODULE = "phase3_2e_diagnostics"
DIAGNOSTICS_VERSION = "phase3_2e_diagnostics_v1_protocol_sync_gate_sensitivity"


# =========================================================
# Generic helpers
# =========================================================

def _now_str() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def _json_default(obj: Any) -> Any:
    if isinstance(obj, Path):
        return str(obj)

    if isinstance(obj, (np.integer,)):
        return int(obj)

    if isinstance(obj, (np.floating,)):
        return float(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    try:
        if pd.isna(obj):
            return None
    except Exception:
        pass

    if hasattr(obj, "__dict__"):
        return obj.__dict__

    return str(obj)


def save_json(path: Path, payload: Dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False, default=_json_default)


def load_json(path: Path) -> Dict[str, Any]:
    path = Path(path)

    if not path.exists():
        return {}

    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def load_csv(path: Path) -> pd.DataFrame:
    path = Path(path)

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()
    except Exception:
        return pd.DataFrame()


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default

        x = float(value)

        if not np.isfinite(x):
            return default

        return x

    except Exception:
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if pd.isna(value):
            return default

        return int(value)

    except Exception:
        return default


def _as_bool_series(series: pd.Series) -> pd.Series:
    if series.empty:
        return pd.Series([], dtype=bool)

    if series.dtype == bool:
        return series

    return series.astype(str).str.lower().isin(["true", "1", "yes", "y"])


def _numeric_series(df: pd.DataFrame, col: str, default: float = 0.0) -> pd.Series:
    if df.empty:
        return pd.Series([], dtype=float)

    if col not in df.columns:
        return pd.Series([default] * len(df), index=df.index, dtype=float)

    return pd.to_numeric(df[col], errors="coerce").fillna(default)


def _safe_records(df: pd.DataFrame) -> List[Dict[str, Any]]:
    if df.empty:
        return []

    return df.replace({np.nan: None}).to_dict(orient="records")


def _select_existing_columns(df: pd.DataFrame, columns: List[str]) -> List[str]:
    return [c for c in columns if c in df.columns]


def _status_from_payload(payload: Mapping[str, Any]) -> str:
    if not payload:
        return "missing"

    return str(payload.get("status", payload.get("result", {}).get("status", "unknown")))


def _payload_result(payload: Mapping[str, Any]) -> Dict[str, Any]:
    if not payload:
        return {}

    result = payload.get("result", {})

    return result if isinstance(result, dict) else {}


def _payload_summary(payload: Mapping[str, Any]) -> Dict[str, Any]:
    if not payload:
        return {}

    summary = payload.get("summary", {})

    return summary if isinstance(summary, dict) else {}


def _is_protocol_only_payload(payload: Mapping[str, Any]) -> bool:
    if not payload:
        return False

    result = _payload_result(payload)

    if bool(result.get("protocol_only", False)):
        return True

    if str(payload.get("status", "")).lower() == "pending_synchronized_data":
        return True

    return False


def _file_status(path: Path) -> Dict[str, Any]:
    path = Path(path)

    return {
        "path": str(path),
        "exists": bool(path.exists()),
        "size_bytes": int(path.stat().st_size) if path.exists() else 0,
    }


# =========================================================
# Paths
# =========================================================

def phase3_2e_paths(cfg: Phase32EConfig) -> Dict[str, Path]:
    results_dir = Path(cfg.results_dir)
    interim_dir = Path(cfg.interim_dir)

    diagnostics_dir = Path(
        getattr(
            cfg,
            "diagnostics_dir",
            results_dir / "diagnostics",
        )
    )

    raw_sync_csv = Path(
        getattr(
            cfg,
            "synchronized_input_csv",
            Path("data") / "raw" / "phase3_2e" / "synchronized" / "phase3_2e_synchronized_input.csv",
        )
    )

    lagged_frames_dir = Path(
        getattr(
            cfg,
            "lagged_frames_dir",
            interim_dir / "lagged_frames",
        )
    )

    return {
        # Protocol / input
        "synchronized_input_csv": raw_sync_csv,

        # Schema / sync validator
        "schema_report": results_dir / "phase3_2e_schema_report.json",
        "schema_summary": results_dir / "phase3_2e_schema_summary.txt",
        "sync_validation_report": results_dir / "phase3_2e_sync_validation_report.json",
        "sync_validation_summary": results_dir / "phase3_2e_sync_validation_summary.txt",

        # Loader
        "loaded_windows": interim_dir / "phase3_2e_loaded_synchronized_windows.csv",
        "loader_metadata": interim_dir / "phase3_2e_loader_metadata.json",
        "loader_report": results_dir / "phase3_2e_loader_report.json",
        "loader_summary": results_dir / "phase3_2e_loader_summary.txt",

        # Windows
        "windows": interim_dir / "phase3_2e_windows.csv",
        "window_inventory": interim_dir / "phase3_2e_window_inventory.csv",
        "windows_report": results_dir / "phase3_2e_windows_report.json",
        "windows_summary": results_dir / "phase3_2e_windows_summary.txt",

        # Features
        "features": interim_dir / "phase3_2e_features.csv",
        "feature_specs": interim_dir / "phase3_2e_feature_specs.json",
        "features_report": results_dir / "phase3_2e_features_report.json",
        "features_summary": results_dir / "phase3_2e_features_summary.txt",

        # Alignment
        "alignment_inventory": interim_dir / "phase3_2e_alignment_inventory.csv",
        "alignment_metadata": interim_dir / "phase3_2e_alignment_metadata.json",
        "alignment_report": results_dir / "phase3_2e_alignment_report.json",
        "alignment_summary": results_dir / "phase3_2e_alignment_summary.txt",
        "lagged_frames_dir": lagged_frames_dir,

        # Conditional
        "conditional_model_scores": Path(
            getattr(
                cfg,
                "conditional_model_scores_csv",
                results_dir / "phase3_2e_conditional_model_scores.csv",
            )
        ),
        "conditional_pair_scores": Path(
            getattr(
                cfg,
                "conditional_pair_scores_csv",
                results_dir / "phase3_2e_conditional_pair_scores.csv",
            )
        ),
        "conditional_summary_json": Path(
            getattr(
                cfg,
                "conditional_summary_json",
                results_dir / "phase3_2e_conditional_summary.json",
            )
        ),
        "conditional_summary_txt": Path(
            getattr(
                cfg,
                "conditional_summary_txt",
                results_dir / "phase3_2e_conditional_summary.txt",
            )
        ),
        "conditional_report": results_dir / "phase3_2e_conditional_report.json",

        # Controls
        "control_runs": Path(
            getattr(
                cfg,
                "control_runs_csv",
                results_dir / "phase3_2e_control_runs.csv",
            )
        ),
        "control_pair_scores": Path(
            getattr(
                cfg,
                "control_pair_scores_csv",
                results_dir / "phase3_2e_control_pair_scores.csv",
            )
        ),
        "controls_json": Path(
            getattr(
                cfg,
                "controls_json",
                results_dir / "phase3_2e_controls.json",
            )
        ),
        "controls_summary": Path(
            getattr(
                cfg,
                "controls_summary_txt",
                results_dir / "phase3_2e_controls_summary.txt",
            )
        ),
        "controls_report": results_dir / "phase3_2e_controls_report.json",

        # Metrics / gates
        "gates_json": Path(
            getattr(
                cfg,
                "gates_json",
                results_dir / "phase3_2e_gates.json",
            )
        ),
        "metrics_table": results_dir / "phase3_2e_metrics_table.csv",
        "metrics_summary": results_dir / "phase3_2e_metrics_summary.txt",
        "metrics_report": results_dir / "phase3_2e_metrics_report.json",
        "multiple_comparison_guard": Path(
            getattr(
                cfg,
                "multiple_comparison_guard_json",
                results_dir / "phase3_2e_multiple_comparison_guard.json",
            )
        ),

        # Gate sensitivity
        "gate_sensitivity_report": results_dir / "phase3_2e_gate_sensitivity_report.json",
        "gate_sensitivity_summary": results_dir / "phase3_2e_gate_sensitivity_summary.txt",
        "f7_sensitivity": results_dir / "phase3_2e_f7_subject_sensitivity.csv",
        "f8_sensitivity": results_dir / "phase3_2e_f8_complexity_sensitivity.csv",
        "f12_sensitivity": results_dir / "phase3_2e_f12_epsilon_saturation_sensitivity.csv",

        # Diagnostics output dir
        "diagnostics_dir": diagnostics_dir,
    }


# =========================================================
# Conditional row selectors
# =========================================================

def valid_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    if pair_df.empty or "valid" not in pair_df.columns:
        return pd.DataFrame()

    return pair_df[_as_bool_series(pair_df["valid"])].copy()


def primary_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty or "primary" not in valid.columns:
        return pd.DataFrame()

    return valid[_as_bool_series(valid["primary"])].copy()


def multichannel_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    if "multichannel" in valid.columns:
        return valid[_as_bool_series(valid["multichannel"])].copy()

    mask = pd.Series(np.zeros(len(valid), dtype=bool), index=valid.index)

    for col in ["baseline_model", "augmented_model", "family"]:
        if col not in valid.columns:
            continue

        text = valid[col].astype(str)

        mask |= text.str.contains("MCEEG", case=False, na=False)
        mask |= text.str.contains("MC_EEG", case=False, na=False)
        mask |= text.str.contains("multichannel", case=False, na=False)
        mask |= text.str.startswith("E4")
        mask |= text.str.startswith("E5")
        mask |= text.str.startswith("E6")

    return valid[mask].copy()


def single_channel_pair_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    mc = multichannel_pair_rows(valid)

    if mc.empty:
        return valid.copy()

    return valid[~valid.index.isin(set(mc.index.tolist()))].copy()


def positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    return valid[_numeric_series(valid, "conditional_lift") > 0.0].copy()


def primary_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    primary = primary_pair_rows(pair_df)

    if primary.empty:
        return pd.DataFrame()

    return primary[_numeric_series(primary, "conditional_lift") > 0.0].copy()


def multichannel_positive_lift_rows(pair_df: pd.DataFrame) -> pd.DataFrame:
    mc = multichannel_pair_rows(pair_df)

    if mc.empty:
        return pd.DataFrame()

    return mc[_numeric_series(mc, "conditional_lift") > 0.0].copy()


def strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32EConfig) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    required = [
        "conditional_lift",
        "augmented_eps_test",
        "fraction_positive_lift",
        "bic_improvement",
    ]

    if any(col not in valid.columns for col in required):
        return pd.DataFrame()

    return valid[
        (_numeric_series(valid, "conditional_lift") >= float(cfg.conditional_lift_min))
        & (_numeric_series(valid, "augmented_eps_test") >= float(cfg.strong_eps_min))
        & (_numeric_series(valid, "fraction_positive_lift") >= float(cfg.subject_effect_fraction))
        & (_numeric_series(valid, "bic_improvement") >= 0.0)
    ].copy()


def primary_strong_candidate_rows(pair_df: pd.DataFrame, cfg: Phase32EConfig) -> pd.DataFrame:
    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty or "primary" not in strong.columns:
        return pd.DataFrame()

    return strong[_as_bool_series(strong["primary"])].copy()


def exploratory_lift_rows(pair_df: pd.DataFrame, cfg: Phase32EConfig) -> pd.DataFrame:
    positive = positive_lift_rows(pair_df)

    if positive.empty:
        return pd.DataFrame()

    strong = strong_candidate_rows(pair_df, cfg)

    if strong.empty:
        return positive.copy()

    return positive[~positive.index.isin(set(strong.index.tolist()))].copy()


def high_epsilon_zero_lift_rows(pair_df: pd.DataFrame, cfg: Phase32EConfig) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    eps_threshold = float(getattr(cfg, "eps_saturation_value", 0.80))

    eps = _numeric_series(valid, "augmented_eps_test")
    lift = _numeric_series(valid, "conditional_lift")

    return valid[(eps >= eps_threshold) & (lift <= 0.0)].copy()


def best_rows_by_metric(pair_df: pd.DataFrame) -> pd.DataFrame:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return pd.DataFrame()

    metrics = [
        ("conditional_lift", True),
        ("augmented_eps_test", True),
        ("baseline_eps_test", True),
        ("ll_improvement", True),
        ("bic_improvement", True),
        ("aic_improvement", True),
        ("fraction_positive_lift", True),
    ]

    rows: List[Dict[str, Any]] = []

    for metric, descending in metrics:
        if metric not in valid.columns:
            continue

        sorted_df = valid.sort_values(metric, ascending=not descending).reset_index(drop=True)

        if sorted_df.empty:
            continue

        row = sorted_df.iloc[0].to_dict()
        row["selected_by"] = metric
        rows.append(row)

    if not rows:
        return pd.DataFrame()

    best_df = pd.DataFrame(rows)

    preferred_columns = [
        "selected_by",
        "window_seconds",
        "lag_windows",
        "lag_seconds",
        "lag_direction",
        "alignment_scope",
        "family",
        "baseline_model",
        "augmented_model",
        "primary",
        "multichannel",
        "valid",
        "baseline_eps_test",
        "augmented_eps_test",
        "conditional_lift",
        "fraction_positive_lift",
        "ll_improvement",
        "bic_improvement",
        "aic_improvement",
        "n_subjects_evaluated",
        "n_subjects_positive_lift",
        "reason",
    ]

    cols = _select_existing_columns(best_df, preferred_columns)

    return best_df[cols].copy()


# =========================================================
# Artifact diagnostics
# =========================================================

def summarize_stage_payload(
    name: str,
    payload: Mapping[str, Any],
    expected_status_if_missing: str = "missing",
) -> Dict[str, Any]:
    if not payload:
        return {
            "stage": name,
            "available": False,
            "status": expected_status_if_missing,
            "protocol_only": False,
            "result": {},
            "summary": {},
            "interpretation": "Stage payload is missing.",
        }

    result = _payload_result(payload)
    summary = _payload_summary(payload)

    return {
        "stage": name,
        "available": True,
        "status": _status_from_payload(payload),
        "protocol_only": _is_protocol_only_payload(payload),
        "result": result,
        "summary": summary,
        "interpretation": result.get(
            "interpretation",
            payload.get("interpretation", summary.get("interpretation", "")),
        ),
    }


def summarize_protocol_readiness(
    cfg: Phase32EConfig,
    paths: Mapping[str, Path],
    schema_payload: Mapping[str, Any],
    sync_payload: Mapping[str, Any],
    loader_payload: Mapping[str, Any],
    windows_payload: Mapping[str, Any],
    features_payload: Mapping[str, Any],
    alignment_payload: Mapping[str, Any],
) -> Dict[str, Any]:
    input_file = Path(paths["synchronized_input_csv"])

    schema_status = summarize_stage_payload("schema", schema_payload)
    sync_status = summarize_stage_payload("sync_validation", sync_payload)
    loader_status = summarize_stage_payload("loader", loader_payload)
    windows_status = summarize_stage_payload("windows", windows_payload)
    features_status = summarize_stage_payload("features", features_payload)
    alignment_status = summarize_stage_payload("alignment", alignment_payload)

    stage_statuses = [
        schema_status,
        sync_status,
        loader_status,
        windows_status,
        features_status,
        alignment_status,
    ]

    any_protocol_only = any(item.get("protocol_only", False) for item in stage_statuses)

    empirical_ready_flags = [
        bool(schema_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
        bool(sync_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
        bool(loader_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
        bool(windows_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
        bool(features_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
        bool(alignment_status.get("result", {}).get("can_proceed_to_empirical_cdr", False)),
    ]

    can_empirical = bool(all(empirical_ready_flags)) if empirical_ready_flags else False

    if not input_file.exists():
        status = getattr(cfg, "status_pending_synchronized_data", "pending_synchronized_data")
        interpretation = (
            "No synchronized EEG–QRNG input CSV exists. Phase III.2E is valid as "
            "a protocol-only implementation, but empirical CDR is blocked."
        )
    elif can_empirical:
        status = "empirical_sync_ready"
        interpretation = (
            "Synchronized EEG–QRNG input exists and upstream stages report empirical readiness."
        )
    else:
        status = "sync_pipeline_not_empirically_ready"
        interpretation = (
            "A synchronized input path may exist, but one or more upstream stages do not "
            "report empirical readiness."
        )

    return {
        "status": status,
        "synchronized_input": _file_status(input_file),
        "allow_protocol_only_without_data": bool(getattr(cfg, "allow_protocol_only_without_data", True)),
        "require_real_synchronized_data_for_claim": bool(getattr(cfg, "require_real_synchronized_data_for_claim", True)),
        "any_protocol_only_stage": bool(any_protocol_only),
        "can_proceed_to_empirical_cdr": bool(can_empirical),
        "stages": stage_statuses,
        "interpretation": interpretation,
    }


def summarize_loader_window_feature_alignment_tables(
    loaded_df: pd.DataFrame,
    windows_df: pd.DataFrame,
    features_df: pd.DataFrame,
    alignment_inventory_df: pd.DataFrame,
) -> Dict[str, Any]:
    out: Dict[str, Any] = {
        "loaded_windows_rows": int(len(loaded_df)),
        "windows_rows": int(len(windows_df)),
        "features_rows": int(len(features_df)),
        "alignment_inventory_rows": int(len(alignment_inventory_df)),
    }

    for name, df in [
        ("loaded", loaded_df),
        ("windows", windows_df),
        ("features", features_df),
        ("alignment_inventory", alignment_inventory_df),
    ]:
        if df.empty:
            out[f"{name}_subjects"] = 0
            out[f"{name}_sessions"] = 0
            continue

        out[f"{name}_subjects"] = (
            int(df["subject_id"].nunique())
            if "subject_id" in df.columns
            else 0
        )

        out[f"{name}_sessions"] = (
            int(df[["subject_id", "session_id"]].drop_duplicates().shape[0])
            if {"subject_id", "session_id"}.issubset(df.columns)
            else 0
        )

    if not alignment_inventory_df.empty:
        for col in [
            "n_valid_alignment_rows",
            "n_valid_primary_alignment_rows",
            "n_valid_conditional_rows",
            "n_valid_mc_conditional_rows",
        ]:
            if col in alignment_inventory_df.columns:
                out[f"alignment_total_{col}"] = int(
                    pd.to_numeric(alignment_inventory_df[col], errors="coerce").fillna(0).sum()
                )

        if "alignment_scope" in alignment_inventory_df.columns:
            out["alignment_scope_counts"] = (
                alignment_inventory_df["alignment_scope"]
                .fillna("")
                .astype(str)
                .value_counts()
                .to_dict()
            )

        if "lag_direction" in alignment_inventory_df.columns:
            out["lag_direction_counts"] = (
                alignment_inventory_df["lag_direction"]
                .fillna("")
                .astype(str)
                .value_counts()
                .to_dict()
            )

    return out


# =========================================================
# Conditional diagnostics
# =========================================================

def summarize_model_saturation(model_df: pd.DataFrame, cfg: Phase32EConfig) -> Dict[str, Any]:
    if model_df.empty:
        return {
            "available": False,
            "reason": "model_scores_missing_or_empty",
        }

    eps_saturation_value = float(getattr(cfg, "eps_saturation_value", 0.80))
    warning_fraction = float(getattr(cfg, "eps_saturation_warning_fraction", 0.50))

    eps_cols = [
        col for col in ["eps_candidate", "eps_calib", "eps_test"]
        if col in model_df.columns
    ]

    if not eps_cols:
        return {
            "available": False,
            "reason": "no_epsilon_columns_available",
        }

    columns: Dict[str, Any] = {}

    max_fraction = 0.0

    for col in eps_cols:
        values = _numeric_series(model_df, col)
        saturated = values >= eps_saturation_value

        sat_fraction = float(np.mean(saturated.to_numpy(dtype=bool))) if len(saturated) else 0.0

        max_fraction = max(max_fraction, sat_fraction)

        columns[col] = {
            "max": float(values.max()) if len(values) else 0.0,
            "mean": float(values.mean()) if len(values) else 0.0,
            "median": float(values.median()) if len(values) else 0.0,
            "n_saturated": int(saturated.sum()),
            "saturation_fraction": sat_fraction,
        }

    return {
        "available": True,
        "eps_saturation_value": eps_saturation_value,
        "warning_fraction": warning_fraction,
        "n_model_rows": int(len(model_df)),
        "columns": columns,
        "max_saturation_fraction": float(max_fraction),
        "warning": bool(max_fraction >= warning_fraction),
        "reason": "epsilon_saturation_warning" if max_fraction >= warning_fraction else "ok",
    }


def summarize_pair_saturation(pair_df: pd.DataFrame, cfg: Phase32EConfig) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)

    if valid.empty:
        return {
            "available": False,
            "reason": "no_valid_pair_rows",
        }

    eps_saturation_value = float(getattr(cfg, "eps_saturation_value", 0.80))
    warning_fraction = float(getattr(cfg, "eps_saturation_warning_fraction", 0.50))

    baseline_eps = _numeric_series(valid, "baseline_eps_test")
    augmented_eps = _numeric_series(valid, "augmented_eps_test")

    baseline_sat = baseline_eps >= eps_saturation_value
    augmented_sat = augmented_eps >= eps_saturation_value
    either_sat = baseline_sat | augmented_sat
    both_sat = baseline_sat & augmented_sat

    either_fraction = float(np.mean(either_sat.to_numpy(dtype=bool))) if len(either_sat) else 0.0
    both_fraction = float(np.mean(both_sat.to_numpy(dtype=bool))) if len(both_sat) else 0.0

    return {
        "available": True,
        "eps_saturation_value": eps_saturation_value,
        "warning_fraction": warning_fraction,
        "n_valid_pair_rows": int(len(valid)),
        "max_baseline_eps_test": float(baseline_eps.max()) if len(baseline_eps) else 0.0,
        "max_augmented_eps_test": float(augmented_eps.max()) if len(augmented_eps) else 0.0,
        "n_either_saturated": int(either_sat.sum()),
        "n_both_saturated": int(both_sat.sum()),
        "either_saturation_fraction": either_fraction,
        "both_saturation_fraction": both_fraction,
        "warning": bool(either_fraction >= warning_fraction),
        "reason": "pair_level_epsilon_saturation_warning" if either_fraction >= warning_fraction else "ok",
    }


def summarize_conditional(
    pair_df: pd.DataFrame,
    model_df: pd.DataFrame,
    conditional_payload: Mapping[str, Any],
    cfg: Phase32EConfig,
) -> Dict[str, Any]:
    valid = valid_pair_rows(pair_df)
    primary = primary_pair_rows(pair_df)
    positive = positive_lift_rows(pair_df)
    primary_positive = primary_positive_lift_rows(pair_df)
    strong = strong_candidate_rows(pair_df, cfg)
    primary_strong = primary_strong_candidate_rows(pair_df, cfg)
    exploratory = exploratory_lift_rows(pair_df, cfg)
    high_eps_zero_lift = high_epsilon_zero_lift_rows(pair_df, cfg)

    single_channel = single_channel_pair_rows(pair_df)
    multichannel = multichannel_pair_rows(pair_df)
    multichannel_positive = multichannel_positive_lift_rows(pair_df)

    protocol_only = _is_protocol_only_payload(conditional_payload)

    summary: Dict[str, Any] = {
        "available": not pair_df.empty or bool(conditional_payload),
        "protocol_only": bool(protocol_only),
        "status": _status_from_payload(conditional_payload),
        "n_model_rows": int(len(model_df)),
        "n_rows": int(len(pair_df)),
        "n_valid_rows": int(len(valid)),
        "n_primary_rows": int(len(primary)),
        "n_positive_lift_rows": int(len(positive)),
        "n_primary_positive_lift_rows": int(len(primary_positive)),
        "n_exploratory_lift_rows": int(len(exploratory)),
        "n_strong_candidate_rows": int(len(strong)),
        "n_primary_strong_candidate_rows": int(len(primary_strong)),
        "n_high_epsilon_zero_lift_rows": int(len(high_eps_zero_lift)),
        "n_single_channel_rows": int(len(single_channel)),
        "n_multichannel_rows": int(len(multichannel)),
        "n_multichannel_positive_lift_rows": int(len(multichannel_positive)),
        "thresholds": {
            "conditional_lift_min": float(cfg.conditional_lift_min),
            "strong_eps_min": float(cfg.strong_eps_min),
            "subject_effect_fraction": float(cfg.subject_effect_fraction),
            "eps_saturation_value": float(getattr(cfg, "eps_saturation_value", 0.80)),
        },
        "model_saturation": summarize_model_saturation(model_df, cfg),
        "pair_saturation": summarize_pair_saturation(pair_df, cfg),
        "best_rows_by_metric": _safe_records(best_rows_by_metric(pair_df)),
        "primary_rows": _safe_records(primary),
        "positive_lift_rows": _safe_records(positive),
        "primary_positive_lift_rows": _safe_records(primary_positive),
        "exploratory_lift_rows": _safe_records(exploratory),
        "strong_candidate_rows": _safe_records(strong),
        "primary_strong_candidate_rows": _safe_records(primary_strong),
        "high_epsilon_zero_lift_rows": _safe_records(high_eps_zero_lift),
    }

    if valid.empty:
        if protocol_only:
            summary["interpretation"] = (
                "Conditional CDR is in protocol-only mode. No synchronized EEG–QRNG "
                "pair rows exist yet."
            )
        else:
            summary["interpretation"] = (
                "No valid synchronized conditional pair rows were available."
            )

        return summary

    lift = _numeric_series(valid, "conditional_lift")
    eps = _numeric_series(valid, "augmented_eps_test")
    frac = _numeric_series(valid, "fraction_positive_lift")
    bic = _numeric_series(valid, "bic_improvement")
    ll = _numeric_series(valid, "ll_improvement")

    summary.update(
        {
            "max_conditional_lift": float(lift.max()) if len(lift) else 0.0,
            "max_augmented_eps_test": float(eps.max()) if len(eps) else 0.0,
            "max_fraction_positive_lift": float(frac.max()) if len(frac) else 0.0,
            "best_bic_improvement": float(bic.max()) if len(bic) else 0.0,
            "best_ll_improvement": float(ll.max()) if len(ll) else 0.0,
        }
    )

    if len(primary_strong) > 0:
        summary["interpretation"] = (
            "At least one primary synchronized strong candidate row exists before "
            "final replication review."
        )
    elif len(strong) > 0:
        summary["interpretation"] = (
            "Strong candidate rows exist only outside the registered primary structure."
        )
    elif len(positive) > 0:
        summary["interpretation"] = (
            "Positive synchronized conditional lift rows exist, but they remain "
            "exploratory unless all gates and controls pass."
        )
    else:
        summary["interpretation"] = (
            "No positive synchronized conditional lift rows were detected."
        )

    return summary


# =========================================================
# Control diagnostics
# =========================================================

def summarize_control_runs(control_runs_df: pd.DataFrame, controls_payload: Mapping[str, Any], cfg: Phase32EConfig) -> Dict[str, Any]:
    if control_runs_df.empty:
        return {
            "available": bool(controls_payload),
            "protocol_only": _is_protocol_only_payload(controls_payload),
            "status": _status_from_payload(controls_payload),
            "n_control_runs": 0,
            "n_valid_control_runs": 0,
            "n_control_types": 0,
            "failed_control_types": _payload_result(controls_payload).get("failed_control_types", []),
            "required_control_types": _payload_summary(controls_payload).get(
                "required_control_types",
                getattr(cfg, "required_control_types", []),
            ),
            "interpretation": (
                "Controls are protocol-only or unavailable because no synchronized "
                "alignment frames exist."
            ),
        }

    rows: List[Dict[str, Any]] = []

    for control_type, group in control_runs_df.groupby("control_type", sort=True):
        valid = group[_as_bool_series(group["valid"])] if "valid" in group.columns else group.copy()

        if valid.empty:
            rows.append(
                {
                    "control_type": str(control_type),
                    "n_runs": int(len(group)),
                    "n_valid_runs": 0,
                    "fraction_collapsed_overall": 0.0,
                    "passed_estimate": False,
                    "reason": "no_valid_runs",
                }
            )
            continue

        if "collapsed_overall" in valid.columns:
            collapsed = _as_bool_series(valid["collapsed_overall"])
        else:
            lift = _numeric_series(valid, "max_conditional_lift")
            bic = _numeric_series(valid, "max_bic_improvement")
            frac = _numeric_series(valid, "max_fraction_positive_lift")
            n_strong = _numeric_series(valid, "n_strong_candidate_rows")
            collapsed = (
                (lift <= float(cfg.control_tol))
                & (bic <= 0.0)
                & (frac < float(cfg.subject_effect_fraction))
                & (n_strong.astype(int) == 0)
            )

        fraction_collapsed = float(np.mean(collapsed.to_numpy(dtype=bool))) if len(collapsed) else 0.0
        passed_estimate = fraction_collapsed >= float(getattr(cfg, "required_control_fraction", 1.0))

        rows.append(
            {
                "control_type": str(control_type),
                "n_runs": int(len(group)),
                "n_valid_runs": int(len(valid)),
                "median_max_augmented_eps_test": float(_numeric_series(valid, "max_augmented_eps_test").median()),
                "max_augmented_eps_test": float(_numeric_series(valid, "max_augmented_eps_test").max()),
                "median_max_lift": float(_numeric_series(valid, "max_conditional_lift").median()),
                "max_lift": float(_numeric_series(valid, "max_conditional_lift").max()),
                "median_max_bic_improvement": float(_numeric_series(valid, "max_bic_improvement").median()),
                "max_bic_improvement": float(_numeric_series(valid, "max_bic_improvement").max()),
                "fraction_collapsed_overall": fraction_collapsed,
                "required_control_fraction": float(getattr(cfg, "required_control_fraction", 1.0)),
                "control_tol": float(getattr(cfg, "control_tol", 0.05)),
                "passed_estimate": bool(passed_estimate),
                "reason": "ok" if passed_estimate else "control_effect_survived",
            }
        )

    breakdown = pd.DataFrame(rows)
    failed = breakdown[breakdown["passed_estimate"] == False].copy()

    return {
        "available": True,
        "protocol_only": _is_protocol_only_payload(controls_payload),
        "status": _status_from_payload(controls_payload),
        "n_control_runs": int(len(control_runs_df)),
        "n_valid_control_runs": int(_as_bool_series(control_runs_df["valid"]).sum()) if "valid" in control_runs_df.columns else int(len(control_runs_df)),
        "n_control_types": int(len(breakdown)),
        "n_failed_control_types": int(len(failed)),
        "failed_control_types": failed["control_type"].tolist() if not failed.empty else [],
        "required_control_types": _payload_summary(controls_payload).get(
            "required_control_types",
            getattr(cfg, "required_control_types", []),
        ),
        "control_breakdown": breakdown.to_dict(orient="records"),
        "interpretation": (
            "All synchronized negative controls collapsed under the official criteria."
            if failed.empty
            else "At least one synchronized negative control did not collapse."
        ),
    }


# =========================================================
# Gates / sensitivity diagnostics
# =========================================================

def summarize_gates(gates_payload: Mapping[str, Any], metrics_table_df: pd.DataFrame) -> Dict[str, Any]:
    if gates_payload:
        final_status = gates_payload.get("final_status", {})
        gates = gates_payload.get("gates", [])
        epsilon_saturation = gates_payload.get("epsilon_saturation", {})
    else:
        final_status = {}
        gates = metrics_table_df.to_dict(orient="records") if not metrics_table_df.empty else []
        epsilon_saturation = {}

    passed: List[str] = []
    failed: List[str] = []
    not_evaluated: List[str] = []
    warnings: List[str] = []

    for gate in gates:
        status = str(gate.get("status", "")).upper()
        gate_id = str(gate.get("gate", ""))

        if status == "PASS":
            passed.append(gate_id)
        elif status == "FAIL":
            failed.append(gate_id)
        elif status == "NOT_EVALUATED":
            not_evaluated.append(gate_id)
        elif status == "WARN":
            warnings.append(gate_id)

    return {
        "available": bool(gates),
        "final_status": final_status,
        "status": final_status.get("status", gates_payload.get("status") if gates_payload else "missing"),
        "protocol_only": bool(final_status.get("protocol_only", False)),
        "can_claim_empirical_cdr": bool(final_status.get("can_claim_empirical_cdr", False)),
        "passed_gates": passed,
        "failed_gates": failed,
        "not_evaluated_gates": not_evaluated,
        "warning_gates": warnings,
        "gates": gates,
        "epsilon_saturation": epsilon_saturation,
    }


def summarize_gate_sensitivity(
    sensitivity_payload: Mapping[str, Any],
    f7_df: pd.DataFrame,
    f8_df: pd.DataFrame,
    f12_df: pd.DataFrame,
) -> Dict[str, Any]:
    if not sensitivity_payload:
        return {
            "available": False,
            "status": "missing",
            "protocol_only": False,
            "interpretation": "Gate sensitivity report is missing.",
        }

    result = _payload_result(sensitivity_payload)

    return {
        "available": True,
        "status": str(sensitivity_payload.get("status", result.get("status", "unknown"))),
        "protocol_only": bool(result.get("protocol_only", False)),
        "can_proceed_to_diagnostics": bool(result.get("can_proceed_to_diagnostics", True)),
        "can_claim_empirical_cdr": bool(result.get("can_claim_empirical_cdr", False)),
        "official_gate_statuses": sensitivity_payload.get("official_gate_statuses", {}),
        "f7_subject_consistency": sensitivity_payload.get("f7_subject_consistency", {}),
        "f8_complexity_penalty": sensitivity_payload.get("f8_complexity_penalty", {}),
        "f12_epsilon_saturation": sensitivity_payload.get("f12_epsilon_saturation", {}),
        "f7_rows": int(len(f7_df)),
        "f8_rows": int(len(f8_df)),
        "f12_rows": int(len(f12_df)),
        "interpretation": result.get(
            "interpretation",
            sensitivity_payload.get("interpretation", ""),
        ),
    }


# =========================================================
# Multiple-comparison guard
# =========================================================

def summarize_multiple_comparison_guard(mc_guard: Mapping[str, Any]) -> Dict[str, Any]:
    if not mc_guard:
        return {
            "available": False,
            "reason": "multiple_comparison_guard_missing",
        }

    return {
        "available": True,
        "enabled": bool(mc_guard.get("enabled", True)),
        "n_valid_tests": _safe_int(mc_guard.get("n_valid_tests")),
        "n_positive_lift_tests": _safe_int(mc_guard.get("n_positive_lift_tests")),
        "n_primary_positive_lift_tests": _safe_int(mc_guard.get("n_primary_positive_lift_tests")),
        "n_exploratory_lift_tests": _safe_int(mc_guard.get("n_exploratory_lift_tests")),
        "n_strong_candidate_tests": _safe_int(mc_guard.get("n_strong_candidate_tests")),
        "n_primary_strong_candidate_tests": _safe_int(mc_guard.get("n_primary_strong_candidate_tests")),
        "n_multichannel_tests": _safe_int(mc_guard.get("n_multichannel_tests")),
        "interpretation": mc_guard.get("interpretation", ""),
    }


# =========================================================
# Final interpretation
# =========================================================

def build_final_diagnostic_interpretation(
    protocol_summary: Mapping[str, Any],
    conditional_summary: Mapping[str, Any],
    controls_summary: Mapping[str, Any],
    gates_summary: Mapping[str, Any],
    sensitivity_summary: Mapping[str, Any],
    cfg: Phase32EConfig,
) -> Dict[str, Any]:
    final_status = gates_summary.get("final_status", {})
    status = str(final_status.get("status", gates_summary.get("status", "unknown")))

    protocol_only = bool(
        protocol_summary.get("any_protocol_only_stage", False)
        or conditional_summary.get("protocol_only", False)
        or controls_summary.get("protocol_only", False)
        or gates_summary.get("protocol_only", False)
        or sensitivity_summary.get("protocol_only", False)
    )

    n_positive = _safe_int(conditional_summary.get("n_positive_lift_rows"))
    n_primary_positive = _safe_int(conditional_summary.get("n_primary_positive_lift_rows"))
    n_strong = _safe_int(conditional_summary.get("n_strong_candidate_rows"))
    n_primary_strong = _safe_int(conditional_summary.get("n_primary_strong_candidate_rows"))
    n_mc_positive = _safe_int(conditional_summary.get("n_multichannel_positive_lift_rows"))

    failed_gates = gates_summary.get("failed_gates", [])
    warning_gates = gates_summary.get("warning_gates", [])
    not_eval = gates_summary.get("not_evaluated_gates", [])

    controls_failed = _safe_int(controls_summary.get("n_failed_control_types")) > 0
    empirical_ready = bool(protocol_summary.get("can_proceed_to_empirical_cdr", False))

    if protocol_only or status == getattr(cfg, "status_pending_synchronized_data", "pending_synchronized_data"):
        headline = "Phase III.2E is protocol-ready but empirically pending synchronized EEG–QRNG data."
        recommendation = (
            "Treat Phase III.2E as a completed protocol implementation, not an empirical "
            "result. The next scientific requirement is a real synchronized EEG + QRNG "
            "dataset with valid timestamp alignment. Do not claim EEG–QRNG coupling from "
            "protocol-only outputs."
        )
    elif n_primary_strong > 0 and not controls_failed and "F12" not in warning_gates:
        headline = "Phase III.2E produced a synchronized primary candidate signal."
        recommendation = (
            "Document this as a candidate synchronized EEG–QRNG signal requiring full "
            "diagnostic review, independent replication and protocol audit."
        )
    elif controls_failed:
        headline = "Phase III.2E is blocked by synchronized negative controls."
        recommendation = (
            "Do not claim a positive signal. Inspect control-level outputs and determine "
            "whether the apparent effect survives broken synchronization."
        )
    elif n_positive > 0:
        headline = "Phase III.2E produced exploratory synchronized conditional leads only."
        recommendation = (
            "Document exploratory leads but do not claim empirical CDR unless controls, "
            "F7, F8, F12 and primary-gate criteria are satisfied."
        )
    else:
        headline = "Phase III.2E produced no positive synchronized conditional lift at the current stage."
        recommendation = (
            "Treat this as a synchronized conditional null only if real synchronized data "
            "were available and controls passed. In protocol-only mode, treat it as pending."
        )

    scientific_read: List[str] = []

    if protocol_only:
        scientific_read.append(
            "The current III.2E execution is protocol-only because no real synchronized EEG–QRNG input CSV is available."
        )
    else:
        scientific_read.append(
            "The current III.2E execution used empirical synchronized rows."
        )

    scientific_read.append(
        f"Protocol empirical readiness: {empirical_ready}."
    )

    scientific_read.append(
        f"Positive conditional lift rows: {n_positive}; primary positive rows: {n_primary_positive}."
    )

    scientific_read.append(
        f"Strong candidate rows: {n_strong}; primary strong candidates: {n_primary_strong}."
    )

    scientific_read.append(
        f"Multichannel synchronized positive lift rows: {n_mc_positive}."
    )

    if failed_gates:
        scientific_read.append(f"Failed official gates: {failed_gates}.")

    if warning_gates:
        scientific_read.append(f"Warning gates: {warning_gates}.")

    if not_eval:
        scientific_read.append(f"Not evaluated gates: {not_eval}.")

    if sensitivity_summary.get("available"):
        scientific_read.append(
            "F7/F8/F12 sensitivity diagnostics were generated without changing official gate thresholds."
        )

    scientific_read.append(
        "A positive claim remains prohibited unless synchronized data exist and all required controls/gates support the result."
    )

    return {
        "headline": headline,
        "status": status,
        "protocol_only": bool(protocol_only),
        "can_claim_empirical_cdr": bool(gates_summary.get("can_claim_empirical_cdr", False)),
        "scientific_read": scientific_read,
        "recommendation": recommendation,
    }


# =========================================================
# Text report
# =========================================================

def build_diagnostics_summary_text(report: Mapping[str, Any]) -> str:
    lines: List[str] = []

    lines.append("=" * 78)
    lines.append("CDR Phase III.2E — Diagnostics Summary")
    lines.append("Synchronized EEG–QRNG protocol and gate-sensitivity version")
    lines.append("=" * 78)
    lines.append("")

    final = report.get("final_interpretation", {})
    lines.append("Final interpretation")
    lines.append("-" * 78)
    lines.append(f"headline: {final.get('headline')}")
    lines.append(f"status: {final.get('status')}")
    lines.append(f"protocol_only: {final.get('protocol_only')}")
    lines.append(f"can_claim_empirical_cdr: {final.get('can_claim_empirical_cdr')}")
    lines.append("")

    for item in final.get("scientific_read", []):
        lines.append(f"- {item}")

    lines.append("")
    lines.append(f"recommendation: {final.get('recommendation')}")
    lines.append("")

    protocol = report.get("protocol_readiness", {})
    lines.append("Protocol readiness")
    lines.append("-" * 78)
    lines.append(f"status: {protocol.get('status')}")
    lines.append(f"synchronized_input: {protocol.get('synchronized_input')}")
    lines.append(f"any_protocol_only_stage: {protocol.get('any_protocol_only_stage')}")
    lines.append(f"can_proceed_to_empirical_cdr: {protocol.get('can_proceed_to_empirical_cdr')}")
    lines.append(f"interpretation: {protocol.get('interpretation')}")
    lines.append("")

    artifacts = report.get("artifact_table_diagnostics", {})
    lines.append("Pipeline table diagnostics")
    lines.append("-" * 78)
    for key, value in artifacts.items():
        lines.append(f"{key}: {value}")
    lines.append("")

    conditional = report.get("conditional_diagnostics", {})
    lines.append("Conditional diagnostics")
    lines.append("-" * 78)
    lines.append(f"status: {conditional.get('status')}")
    lines.append(f"protocol_only: {conditional.get('protocol_only')}")
    lines.append(f"n_model_rows: {conditional.get('n_model_rows')}")
    lines.append(f"n_pair_rows: {conditional.get('n_rows')}")
    lines.append(f"n_valid_rows: {conditional.get('n_valid_rows')}")
    lines.append(f"n_primary_rows: {conditional.get('n_primary_rows')}")
    lines.append(f"n_positive_lift_rows: {conditional.get('n_positive_lift_rows')}")
    lines.append(f"n_primary_positive_lift_rows: {conditional.get('n_primary_positive_lift_rows')}")
    lines.append(f"n_exploratory_lift_rows: {conditional.get('n_exploratory_lift_rows')}")
    lines.append(f"n_strong_candidate_rows: {conditional.get('n_strong_candidate_rows')}")
    lines.append(f"n_primary_strong_candidate_rows: {conditional.get('n_primary_strong_candidate_rows')}")
    lines.append(f"n_high_epsilon_zero_lift_rows: {conditional.get('n_high_epsilon_zero_lift_rows')}")
    lines.append(f"n_single_channel_rows: {conditional.get('n_single_channel_rows')}")
    lines.append(f"n_multichannel_rows: {conditional.get('n_multichannel_rows')}")
    lines.append(f"n_multichannel_positive_lift_rows: {conditional.get('n_multichannel_positive_lift_rows')}")
    lines.append(f"interpretation: {conditional.get('interpretation')}")
    lines.append("")

    pair_sat = conditional.get("pair_saturation", {})
    model_sat = conditional.get("model_saturation", {})
    lines.append("Epsilon saturation")
    lines.append("-" * 78)
    lines.append(f"pair_saturation: {pair_sat}")
    lines.append(f"model_saturation: {model_sat}")
    lines.append("")

    controls = report.get("control_diagnostics", {})
    lines.append("Control diagnostics")
    lines.append("-" * 78)
    lines.append(f"status: {controls.get('status')}")
    lines.append(f"protocol_only: {controls.get('protocol_only')}")
    lines.append(f"available: {controls.get('available')}")
    lines.append(f"n_control_runs: {controls.get('n_control_runs')}")
    lines.append(f"n_valid_control_runs: {controls.get('n_valid_control_runs')}")
    lines.append(f"n_control_types: {controls.get('n_control_types')}")
    lines.append(f"n_failed_control_types: {controls.get('n_failed_control_types')}")
    lines.append(f"failed_control_types: {controls.get('failed_control_types')}")
    lines.append(f"required_control_types: {controls.get('required_control_types')}")
    lines.append(f"interpretation: {controls.get('interpretation')}")
    lines.append("")

    gates = report.get("gates_diagnostics", {})
    lines.append("Official gates")
    lines.append("-" * 78)
    lines.append(f"status: {gates.get('status')}")
    lines.append(f"protocol_only: {gates.get('protocol_only')}")
    lines.append(f"passed_gates: {gates.get('passed_gates')}")
    lines.append(f"failed_gates: {gates.get('failed_gates')}")
    lines.append(f"warning_gates: {gates.get('warning_gates')}")
    lines.append(f"not_evaluated_gates: {gates.get('not_evaluated_gates')}")
    lines.append(f"can_claim_empirical_cdr: {gates.get('can_claim_empirical_cdr')}")
    lines.append("")

    sensitivity = report.get("gate_sensitivity_diagnostics", {})
    lines.append("Gate sensitivity — F7/F8/F12")
    lines.append("-" * 78)
    lines.append(f"status: {sensitivity.get('status')}")
    lines.append(f"protocol_only: {sensitivity.get('protocol_only')}")
    lines.append(f"available: {sensitivity.get('available')}")
    lines.append(f"official_gate_statuses: {sensitivity.get('official_gate_statuses')}")
    lines.append(f"f7_subject_consistency: {sensitivity.get('f7_subject_consistency')}")
    lines.append(f"f8_complexity_penalty: {sensitivity.get('f8_complexity_penalty')}")
    lines.append(f"f12_epsilon_saturation: {sensitivity.get('f12_epsilon_saturation')}")
    lines.append(f"interpretation: {sensitivity.get('interpretation')}")
    lines.append("")

    mc = report.get("multiple_comparison_guard", {})
    lines.append("Multiple-comparison guard")
    lines.append("-" * 78)
    lines.append(f"available: {mc.get('available')}")
    lines.append(f"enabled: {mc.get('enabled')}")
    lines.append(f"n_valid_tests: {mc.get('n_valid_tests')}")
    lines.append(f"n_positive_lift_tests: {mc.get('n_positive_lift_tests')}")
    lines.append(f"n_primary_positive_lift_tests: {mc.get('n_primary_positive_lift_tests')}")
    lines.append(f"n_exploratory_lift_tests: {mc.get('n_exploratory_lift_tests')}")
    lines.append(f"n_strong_candidate_tests: {mc.get('n_strong_candidate_tests')}")
    lines.append(f"n_primary_strong_candidate_tests: {mc.get('n_primary_strong_candidate_tests')}")
    lines.append(f"n_multichannel_tests: {mc.get('n_multichannel_tests')}")
    lines.append("")

    lines.append("=" * 78)

    return "\n".join(lines)


# =========================================================
# Main diagnostics
# =========================================================

def run_phase3_2e_diagnostics(cfg: Optional[Phase32EConfig] = None) -> Dict[str, Any]:
    if cfg is None:
        cfg = load_phase3_2e_config()

    paths = phase3_2e_paths(cfg)
    diagnostics_dir = paths["diagnostics_dir"]
    diagnostics_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 78)
    print("CDR Phase III.2E — Diagnostics")
    print("Synchronized EEG–QRNG protocol and gate-sensitivity version")
    print("=" * 78)

    # -----------------------------------------------------
    # Load JSON payloads
    # -----------------------------------------------------
    schema_payload = load_json(paths["schema_report"])
    sync_payload = load_json(paths["sync_validation_report"])
    loader_payload = load_json(paths["loader_report"])
    windows_payload = load_json(paths["windows_report"])
    features_payload = load_json(paths["features_report"])
    alignment_payload = load_json(paths["alignment_report"])
    conditional_payload = load_json(paths["conditional_report"])
    controls_payload = load_json(paths["controls_json"])
    gates_payload = load_json(paths["gates_json"])
    mc_guard_payload = load_json(paths["multiple_comparison_guard"])
    sensitivity_payload = load_json(paths["gate_sensitivity_report"])

    loader_metadata = load_json(paths["loader_metadata"])
    feature_specs = load_json(paths["feature_specs"])
    alignment_metadata = load_json(paths["alignment_metadata"])

    # -----------------------------------------------------
    # Load CSV tables
    # -----------------------------------------------------
    loaded_df = load_csv(paths["loaded_windows"])
    windows_df = load_csv(paths["windows"])
    features_df = load_csv(paths["features"])
    alignment_inventory_df = load_csv(paths["alignment_inventory"])

    pair_df = load_csv(paths["conditional_pair_scores"])
    model_df = load_csv(paths["conditional_model_scores"])

    control_runs_df = load_csv(paths["control_runs"])
    control_pair_df = load_csv(paths["control_pair_scores"])

    metrics_table_df = load_csv(paths["metrics_table"])

    f7_df = load_csv(paths["f7_sensitivity"])
    f8_df = load_csv(paths["f8_sensitivity"])
    f12_df = load_csv(paths["f12_sensitivity"])

    print(f"[Diagnostics III.2E] loaded rows: {len(loaded_df)}")
    print(f"[Diagnostics III.2E] window rows: {len(windows_df)}")
    print(f"[Diagnostics III.2E] feature rows: {len(features_df)}")
    print(f"[Diagnostics III.2E] alignment inventory rows: {len(alignment_inventory_df)}")
    print(f"[Diagnostics III.2E] conditional model rows: {len(model_df)}")
    print(f"[Diagnostics III.2E] conditional pair rows: {len(pair_df)}")
    print(f"[Diagnostics III.2E] control run rows: {len(control_runs_df)}")
    print(f"[Diagnostics III.2E] control pair rows: {len(control_pair_df)}")
    print(f"[Diagnostics III.2E] metrics table rows: {len(metrics_table_df)}")
    print(f"[Diagnostics III.2E] F7 sensitivity rows: {len(f7_df)}")
    print(f"[Diagnostics III.2E] F8 sensitivity rows: {len(f8_df)}")
    print(f"[Diagnostics III.2E] F12 sensitivity rows: {len(f12_df)}")

    # -----------------------------------------------------
    # Summaries
    # -----------------------------------------------------
    protocol_summary = summarize_protocol_readiness(
        cfg=cfg,
        paths=paths,
        schema_payload=schema_payload,
        sync_payload=sync_payload,
        loader_payload=loader_payload,
        windows_payload=windows_payload,
        features_payload=features_payload,
        alignment_payload=alignment_payload,
    )

    artifact_table_summary = summarize_loader_window_feature_alignment_tables(
        loaded_df=loaded_df,
        windows_df=windows_df,
        features_df=features_df,
        alignment_inventory_df=alignment_inventory_df,
    )

    conditional_summary = summarize_conditional(
        pair_df=pair_df,
        model_df=model_df,
        conditional_payload=conditional_payload,
        cfg=cfg,
    )

    control_summary = summarize_control_runs(
        control_runs_df=control_runs_df,
        controls_payload=controls_payload,
        cfg=cfg,
    )

    gates_summary = summarize_gates(
        gates_payload=gates_payload,
        metrics_table_df=metrics_table_df,
    )

    sensitivity_summary = summarize_gate_sensitivity(
        sensitivity_payload=sensitivity_payload,
        f7_df=f7_df,
        f8_df=f8_df,
        f12_df=f12_df,
    )

    mc_guard_summary = summarize_multiple_comparison_guard(mc_guard_payload)

    final_interpretation = build_final_diagnostic_interpretation(
        protocol_summary=protocol_summary,
        conditional_summary=conditional_summary,
        controls_summary=control_summary,
        gates_summary=gates_summary,
        sensitivity_summary=sensitivity_summary,
        cfg=cfg,
    )

    # -----------------------------------------------------
    # Diagnostic row exports
    # -----------------------------------------------------
    primary_rows_df = primary_pair_rows(pair_df)
    positive_rows_df = positive_lift_rows(pair_df)
    primary_positive_rows_df = primary_positive_lift_rows(pair_df)
    exploratory_rows_df = exploratory_lift_rows(pair_df, cfg)
    strong_rows_df = strong_candidate_rows(pair_df, cfg)
    primary_strong_rows_df = primary_strong_candidate_rows(pair_df, cfg)
    high_eps_zero_lift_df = high_epsilon_zero_lift_rows(pair_df, cfg)
    best_rows_df = best_rows_by_metric(pair_df)
    multichannel_rows_df = multichannel_pair_rows(pair_df)
    multichannel_positive_rows_df = multichannel_positive_lift_rows(pair_df)

    control_breakdown_df = pd.DataFrame(control_summary.get("control_breakdown", []))

    # -----------------------------------------------------
    # Report payload
    # -----------------------------------------------------
    report: Dict[str, Any] = {
        "phase": cfg.phase_name,
        "project_name": cfg.project_name,
        "module": DIAGNOSTICS_MODULE,
        "diagnostics_version": DIAGNOSTICS_VERSION,
        "created_at": _now_str(),
        "source_files": {k: str(v) for k, v in paths.items() if k != "diagnostics_dir"},
        "file_status": {k: _file_status(v) for k, v in paths.items() if k != "diagnostics_dir"},
        "config": describe_config(cfg),
        "protocol_readiness": protocol_summary,
        "stage_payloads": {
            "schema": summarize_stage_payload("schema", schema_payload),
            "sync_validation": summarize_stage_payload("sync_validation", sync_payload),
            "loader": summarize_stage_payload("loader", loader_payload),
            "windows": summarize_stage_payload("windows", windows_payload),
            "features": summarize_stage_payload("features", features_payload),
            "alignment": summarize_stage_payload("alignment", alignment_payload),
            "conditional": summarize_stage_payload("conditional", conditional_payload),
            "controls": summarize_stage_payload("controls", controls_payload),
            "metrics": summarize_stage_payload("metrics", gates_payload),
            "gate_sensitivity": summarize_stage_payload("gate_sensitivity", sensitivity_payload),
        },
        "metadata": {
            "loader_metadata": loader_metadata,
            "feature_specs": feature_specs,
            "alignment_metadata": alignment_metadata,
        },
        "artifact_table_diagnostics": artifact_table_summary,
        "conditional_diagnostics": conditional_summary,
        "control_diagnostics": control_summary,
        "gates_diagnostics": gates_summary,
        "gate_sensitivity_diagnostics": sensitivity_summary,
        "multiple_comparison_guard": mc_guard_summary,
        "final_interpretation": final_interpretation,
    }

    # -----------------------------------------------------
    # Save outputs
    # -----------------------------------------------------
    report_json = diagnostics_dir / "phase3_2e_diagnostics_report.json"
    summary_txt = diagnostics_dir / "phase3_2e_diagnostics_summary.txt"

    primary_csv = diagnostics_dir / "phase3_2e_primary_tests.csv"
    best_csv = diagnostics_dir / "phase3_2e_best_rows.csv"
    positive_csv = diagnostics_dir / "phase3_2e_positive_lift_rows.csv"
    primary_positive_csv = diagnostics_dir / "phase3_2e_primary_positive_lift_rows.csv"
    exploratory_csv = diagnostics_dir / "phase3_2e_exploratory_lift_rows.csv"
    strong_csv = diagnostics_dir / "phase3_2e_strong_candidate_rows.csv"
    primary_strong_csv = diagnostics_dir / "phase3_2e_primary_strong_candidate_rows.csv"
    high_eps_csv = diagnostics_dir / "phase3_2e_high_epsilon_zero_lift_rows.csv"
    multichannel_csv = diagnostics_dir / "phase3_2e_multichannel_rows.csv"
    multichannel_positive_csv = diagnostics_dir / "phase3_2e_multichannel_positive_lift_rows.csv"

    control_breakdown_csv = diagnostics_dir / "phase3_2e_control_breakdown.csv"
    control_pair_copy_csv = diagnostics_dir / "phase3_2e_control_pair_scores_copy.csv"
    gates_copy_csv = diagnostics_dir / "phase3_2e_gates_copy.csv"

    f7_copy_csv = diagnostics_dir / "phase3_2e_f7_subject_sensitivity_copy.csv"
    f8_copy_csv = diagnostics_dir / "phase3_2e_f8_complexity_sensitivity_copy.csv"
    f12_copy_csv = diagnostics_dir / "phase3_2e_f12_epsilon_saturation_sensitivity_copy.csv"

    save_json(report_json, report)

    with open(summary_txt, "w", encoding="utf-8") as f:
        f.write(build_diagnostics_summary_text(report))

    primary_rows_df.to_csv(primary_csv, index=False)
    best_rows_df.to_csv(best_csv, index=False)
    positive_rows_df.to_csv(positive_csv, index=False)
    primary_positive_rows_df.to_csv(primary_positive_csv, index=False)
    exploratory_rows_df.to_csv(exploratory_csv, index=False)
    strong_rows_df.to_csv(strong_csv, index=False)
    primary_strong_rows_df.to_csv(primary_strong_csv, index=False)
    high_eps_zero_lift_df.to_csv(high_eps_csv, index=False)
    multichannel_rows_df.to_csv(multichannel_csv, index=False)
    multichannel_positive_rows_df.to_csv(multichannel_positive_csv, index=False)

    control_breakdown_df.to_csv(control_breakdown_csv, index=False)
    control_pair_df.to_csv(control_pair_copy_csv, index=False)
    metrics_table_df.to_csv(gates_copy_csv, index=False)

    f7_df.to_csv(f7_copy_csv, index=False)
    f8_df.to_csv(f8_copy_csv, index=False)
    f12_df.to_csv(f12_copy_csv, index=False)

    print("\n" + "=" * 78)
    print("Phase III.2E diagnostics completed")
    print("Synchronized EEG–QRNG protocol and gate-sensitivity version")
    print("=" * 78)
    print(f"diagnostics report: {report_json}")
    print(f"diagnostics summary: {summary_txt}")
    print(f"primary tests: {primary_csv}")
    print(f"best rows: {best_csv}")
    print(f"positive lift rows: {positive_csv}")
    print(f"exploratory lift rows: {exploratory_csv}")
    print(f"strong candidate rows: {strong_csv}")
    print(f"multichannel rows: {multichannel_csv}")
    print(f"control breakdown: {control_breakdown_csv}")
    print(f"F7 sensitivity copy: {f7_copy_csv}")
    print(f"F8 sensitivity copy: {f8_copy_csv}")
    print(f"F12 sensitivity copy: {f12_copy_csv}")
    print("=" * 78 + "\n")

    return report


def main() -> None:
    cfg = load_phase3_2e_config()
    report = run_phase3_2e_diagnostics(cfg)

    final = report.get("final_interpretation", {})
    conditional = report.get("conditional_diagnostics", {})
    sensitivity = report.get("gate_sensitivity_diagnostics", {})

    print("Final diagnostic headline:")
    print(final.get("headline"))
    print("")
    print("Phase III.2E conditional summary:")
    print(f"positive lift rows: {conditional.get('n_positive_lift_rows')}")
    print(f"primary positive lift rows: {conditional.get('n_primary_positive_lift_rows')}")
    print(f"strong candidate rows: {conditional.get('n_strong_candidate_rows')}")
    print(f"primary strong candidate rows: {conditional.get('n_primary_strong_candidate_rows')}")
    print("")
    print("Gate sensitivity summary:")
    print(f"status: {sensitivity.get('status')}")
    print(f"protocol_only: {sensitivity.get('protocol_only')}")
    print("")
    print("Recommendation:")
    print(final.get("recommendation"))


if __name__ == "__main__":
    main()